### ISSUE TITLE
filtering monitor data

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1003]
one approach to handling the data set would be to add a filter node to the pipeline, and filter by date.  I tried using a right click to add a filter but no response.  Same thing for trying to add a review node

**Comment by jirhiker** [comment]
I added add review this morning. It was a little flaky. I'll add a GUI for setting up the filtering node

**Comment by wcmcintosh** [comment]
Review nodes adding fine.

Haven't reassessed filters.
