### ISSUE TITLE
Detector Calibration

### ISSUE THREAD

**Issue by jirhiker** [NMGRL/pychron#1004]
add IC runs mixed in with airs, blanks etc. IC run is peak hop run of a few 10's fA on all faradays. I believe matt was convinced that peak hopping yielded per mil level intercalibration. 

IC runs could automatically adjust the gains and/or the analyses could be corrected in data reduction.  
adjustment of J could be used to correct the mass spectrometers for drift over time, locking the cocktail age at 28.201

isn't this a better approach than using cocktails for faraday intercalibration (normalization?) ? I guess it neglects source fractionation but that effect may be negligible.

i can think of some advantages and disadvantages for both approaches

**Comment by wcmcintosh** [comment]
Jake:

	Like you say, this approach has advantages and disadvantages.  

	For either peak hopping or gas mixes, I fell like adjusting the gains and/or IC factors makes more sense and is more direct than adjusting J.

	Using gas mixes corrects for mass discrimination in the detectors(much more of a factor for multipliers than faradays) and in the source.   The other consideration is differences in transmission efficiency for different isotopes at different magnetic field.  I’m not sure what approach is best to address this.

Bill
