### ISSUE TITLE
Remove/Set Invalid Analyses in Fit Flux Editor

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1005]
new option to use browser for flux calculation selection working well

points marked as invalid not being excluded from plot after marking  (or even after deleting them from the analysis list

**Comment by jirhiker** [comment]
which plot

**Comment by wcmcintosh** [comment]
The fit flux plot

**Comment by jirhiker** [comment]
"points marked as invalid not being excluded from plot after marking (or even after deleting them from the analysis list"

Can not replicate this behavior. 1. clicking on point/selected a set of points sets the tag to "omit" using "Set Invalid" is not necessary. 2. deleting analyses from the analysis pane causes flux recalc and the graph to update.

**Comment by wcmcintosh** [comment]
During fit flux editing, is there a way I can set bad analyses to invalid?

**Comment by jirhiker** [comment]
the same ways you set analyses as invalid in an ideogram don't work?
1. select the analyses in the Analyses pane, then use toolbar action "Set Tag", or "Set Invalid"
2. select analyses graphically,                     "                                                                               "
3. right-click analysis, set invalid

**Comment by wcmcintosh** [comment]
Jake:

	When I wrote the ticket, the problem was that after setting analyses invalid, the invalid analyses were not disappearing and the axes were not resizing.

	Omit was working fine, invalid marking was working fine, invalid removal and auto graph replotting was not working.  

	I think that this replot is working fine in the current version, although there appear to be some tagging glitches, ticket submitted.

Bill
