### ISSUE TITLE
Pychron Config Manager

### ISSUE THREAD

**Issue by jirhiker** [NMGRL/pychron#1006]
add something akin to conda but instead of python dependencies download pychron configuration files. 

options to download individual file or directory trees. 
if individual file and -e option used user prompted for information

this should be a separate project from pychron. make a fork of conda and just start hacking away at it. 
conda-pychron

**Comment by jirhiker** [comment]
new project name is `chronda` !!!

**Comment by jirhiker** [comment]
use conda to install packages and anaconda.org to host.

use chronda to create new pychron environments from downloaded packages. 

`chronda create -n Pychron_dev development` == create pychron env Pychron_dev using the development package.

**Comment by wcmcintosh** [comment]
Nice.
