### ISSUE TITLE
experiment error communication

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1028]
Again backing up previously discussed issues with a tickey:

The new big font LASER OFF user communication scheme at the upper left of the PyCO2 screen is fantastic.

Could we expand this idea to Pyexperiment, by vertically shorting the current Wait panel, and using the upper left for big font critical communications with the user, e.g. flaws in the experiment queue such as missing scripts, experiment halted, et

**Comment by jirhiker** [comment]
Not likely to add without further justification. Adding warning messages in most cases has not been of any benefit. All of the items you enumerated are already communicated clearly with popup dialogs
