### ISSUE TITLE
squirrely drop boxes

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1029]
Again as discussed yesterday, it would be great if dropdown text selection boxes could be configured such to disable  scrolling by mouse move alone (no button push)

**Comment by jirhiker** [comment]
removed scroll from drop downs (ComboBox) for all experiment/pipeline items

**Comment by wcmcintosh** [comment]
Script pull downs seem OK.

Extract device still squirrelyy

**Comment by jirhiker** [comment]
could not replicate
