### ISSUE TITLE
plots saved as pdf

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1035]
plots that are saved as pdf

1) open fine in preview
2) open with an error in acrobat and reader and for not show title
3) will not open in illustrator ("Acrobat pdf file format is having difficulties. Too few operands.")

**Comment by wcmcintosh** [comment]
pdfs included in acrobat files can crash acrobat

**Comment by jirhiker** [comment]
i am aware of this issue. a regression error introduced by a dependency. have not looked into a solution

**Comment by jirhiker** [comment]
issue is related to ideograms (or BaseArArFigures) and not PDFGraphicsContext. 

likely a screen to pdf font issue

**Comment by jirhiker** [comment]
issue isolated to labeling peaks
