### ISSUE TITLE
Run list clearing

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1040]
After completing running isotope evolution pipe line, run list is erased.  
Could it be persisted?

**Comment by jirhiker** [comment]
I think that's a misinterpretation of what's actually happening, i.e. run list erased. The runs are not erased, they are just not displayed automatically. As a work around simply toggle between Save Iso and Review and the Analyses list will repopulate

**Comment by wcmcintosh** [comment]
Tested - All seems well now. Close issue?
