### ISSUE TITLE
plotting anything versus anything

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1046]
We have previously discussed plotting anything versus anything. I forgot is there is already a ticket on this.

Matt H would dearly love to plot a time series of cocktail data that includes Radiogenic yield, Age, and centering position. (or other factors that might affect mass spectrometer drift).

How far out is pychron from having this ability?  Beg deal or small deal?

Thanks.

**Comment by jirhiker** [comment]
That is not plotting anything verse anything, that is plotting a time series. Pychron can already plot timeseries. 

Pychron also already has XY Scatter plots which truly allows for anything verse anything plots

**Comment by jirhiker** [comment]
[cocktailtimeseries.pdf](https://github.com/NMGRL/pychron/files/644058/cocktailtimeseries.pdf)

**Comment by jirhiker** [comment]
![cocktailtimeseries](https://cloud.githubusercontent.com/assets/2035568/21076227/75799794-bee3-11e6-8102-b833fc0c85d9.png)

**Comment by wcmcintosh** [comment]
time series does indeed seem to work perfectly here.  Trying X vs Y

**Comment by wcmcintosh** [comment]
Is x vs Y scatter plotting enabled?

**Comment by jirhiker** [comment]
There is a Pipeline Template called XYScatter
