### ISSUE TITLE
blank spectrum

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1075]
I hadn't used the spectrum pipeline for a while.  plotting biotites (e.g. 65496) runs without error, but the spectrum panel is blank

**Comment by jirhiker** [comment]
Check your Spectrum Options. Make sure you have at least "Age Spectrum" set as one of the aux plots.

**Comment by wcmcintosh** [comment]
Age spectrum definitely selected.  Pane appears to be fine and correct integrated age is displayed, and correct age range is selected.  But no data is visible.  I think black is selected as color, not transparent.

**Comment by jirhiker** [comment]
make sure y error is enabled for age spectrum in aux plot
