### ISSUE TITLE
experiment queue precheck failed-showstopper

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1088]
No sure about this repository error

repository identifier = Load1797
repository ids = 1787

[1.pdf](https://github.com/NMGRL/pychron/files/972077/1.pdf)
![1](https://cloud.githubusercontent.com/assets/6482990/25641489/9250509a-2f51-11e7-9e08-3ece619db0aa.png)

**Comment by jirhiker** [comment]
should not be a show stopper. its saying that identifier 65495 was already saved in repo "Load1787" and you are now trying to save the identifier to repo "Load1797". Pychron is giving you an the option to resolve this discrepancy if you want
