### ISSUE TITLE
interpreted age ideogram startup speed

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1103]
when running from home, interpreted age ideogram pipeline is slow to start, I think while it is loading browser data from the database.  I was wondering if this data could be cached, just like the norm analyses

**Comment by wcmcintosh** [comment]
Is the PI/Project etc data now cached?

**Comment by jirhiker** [comment]
browser is only activated once instead of every time the node is configured. so in essence yes to your question
