### ISSUE TITLE
K/Ca log plot minimum

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1121]
in Spectra, if K/Ca is on a log scale and the errors extend <0, the minimum shown on the plot is 1, even if the scale extends to <1.

Shouldn't the error bar extend to the minimum of the plot in this case?\

Not a burning issue at this point - it only affects bad data

**Comment by jirhiker** [comment]
not when the user specifies the limits of the graph

**Comment by wcmcintosh** [comment]
To Clarify - if the error on a K/Ca value takes it into negative space, then the bar plotted on any log scale should extend to the bottom of the graph, regardless of what the user specifies.  Currently, the bar for any negative going value extends from the maximum value down to 1.0, regardless of the minimum value set for the graph.  Am I not correct in my thinking here?

**Comment by jirhiker** [comment]
What does it do for K/Ca values less than 1.0
