### ISSUE TITLE
interpreted age table only finding first entry

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1124]
interpreted age table only finding first entry when there are sixteen

try it with a couple foos

**Comment by wcmcintosh** [comment]
same story with IA ideogram

**Comment by jirhiker** [comment]
Need more information

"interpreted age table only finding first entry" what does this mean. The IA Browser only shows 1 IA when a sample is selected? It all implies that there is only 1 1A not sixteen. Are there 16 files in the ia directory?

**Comment by wcmcintosh** [comment]
A-OK now
