### ISSUE TITLE
Measuring bizarre isotopes

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1175]
See attached screenshot. Instead of measuring typical isotope values (40,39,38,....) values such as 43.962, 42.962 are being collected and saved to the database. See attached screen shot of MassSpec recall window. Unable to collect any data at the moment.

![screen shot 2017-09-01 at 12 53 51 pm](https://user-images.githubusercontent.com/6474471/29984061-cf4ae180-8f15-11e7-8465-2947734581bf.png)

**Comment by jirhiker** [comment]
issue had to do with detector index numbering. Detectors should be numbered in ascending order from high to low mass. e.g. H2 =0, H1=1, AX=2, etc
