### ISSUE TITLE
improve ability to distinguish data on multi-sample plot

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1256]
could you add a legend or other means  to help distinguish results from multiple samples in ideograms or spectra?

currently samples and L#s can be listed in the title, but not readily tied to the different color data points

this could be addressed with a legend

alternatively, if one could add the sample # or L# to the mean age string, this might work well too

**Comment by wcmcintosh** [comment]
Not sure on status of this one.  I had thought that an ideogram legend had been added, but I am not finding it in options.

**Comment by jirhiker** [comment]
"sample # or L# to the mean age string" this was implemented

**Comment by wcmcintosh** [comment]
Labels on mean ages work with one small exception.  If Identifier(Sample) is selected, then the word "Identifier" appears instead of the L#.  If just "Identifier" or "Identifier Sample" is selected, the L# appears in the mean age label.
