### ISSUE TITLE
Group Nodes

### ISSUE THREAD

**Issue by jirhiker** [NMGRL/pychron#1262]
Group Nodes in a single pipeline. only for graphic clarity

**Comment by nmgrluser** [comment]
Is this issue about the folders in the first pipeline node?  If so, it seems like a good organizational tool. Or is it in regard to subgroups in the second pane showing the selected pipeline?  If so, I haven't worked with this feature yet.

**Comment by jirhiker** [comment]
for the latter. and purely for organization
