### ISSUE TITLE
Auto Fit type

### ISSUE THREAD

**Issue by jirhiker** [NMGRL/pychron#1282]
add an auto fit type. 

auto criteria defined in a configuration file
- n<100, linear

**Comment by nmgrluser** [comment]
Interface tested and seems to work well.  I still need to test this with some actual data.  Do you see any reason not to use as our default setting for fitting 40, 39, 36?  One less human to be made.

**Comment by jirhiker** [comment]
there is no default setting inherit to pychron. defaults for fitting are set by the user
