### ISSUE TITLE
Problems with accepting and rejecting points on series

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1287]
When I plot a series (e.g., airs, cocktail) and deselect a point b/c it is an outlier, then refit the regression (e.g., linear to average) the point is reselected automatically and included in the regression. 

Make to where omitted points are always omitted even after refitting the series.

**Comment by jirhiker** [comment]
fix is currently available on release/py3/v18.2

I will be updating argonlab2 to this version
