### ISSUE TITLE
Ideogram not showing the sigma symbol correctly

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1292]
See screen shot.

**Comment by mjz1983** [comment]
![screen shot 2018-02-15 at 9 27 47 am](https://user-images.githubusercontent.com/6474471/36268049-bfbf46c0-1232-11e8-93b0-a9d0b0ab8a0e.png)

**Comment by jirhiker** [comment]
as a temporary fix, set the font to Consolas

**Comment by jirhiker** [comment]
Looks like helvetica and consolas display sigma correctly

menlo and courier dont

**Comment by mjz1983** [comment]
this is computer dependent
