### ISSUE TITLE
Add save as function to the Fit Options window

### ISSUE THREAD

**Issue by nelsiverson** [NMGRL/pychron#1351]
In the Fit Options window, if I want to create my own new template I have to build it from the begging and it would be nice to have a save as option next to the hard disk. That way I can edit the default to my liking and save it is something else. Screen shot is an image of the current blank layout when starting a new template. 

![screen shot 2018-04-11 at 4 53 26 pm](https://user-images.githubusercontent.com/33048412/38647415-67c199e4-3da9-11e8-9ba2-d53b506a666e.png)

**Comment by wcmcintosh** [comment]
Save as added  to iso options.  Seems to work fine. Ready to close.
