### ISSUE TITLE
pull question

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1359]
I did a pull then push for the Tube repository.

Pull yielded the first seven of the ten following lines in Pycharm, then gave me an up-to-date indicator in a small window

Push yielded the next three of the following then lines, but didn't give any feedback on the push

did push work correctly? 

pull 

2018-04-12 13:35:36.718 python[12485:22765064] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
git.cmd                                 : 2018-04-12 13:35:42,436 DEBUG     (MainThread) Popen(['git', 'log', 'master', '--pretty=%H|%cn|%ce|%ct|%s'], cwd=/Users/mcintosh/Pychron_dev/data/.dvc/repositories/Toba, universal_newlines=False, shell=None)
GitRepoManager                          : 2018-04-12 13:35:45,571 DEBUG     (MainThread) ahead behind
git.cmd                                 : 2018-04-12 13:35:45,572 DEBUG     (MainThread) Popen(['git', 'fetch', 'origin'], cwd=/Users/mcintosh/Pychron_dev/data/.dvc/repositories/Toba, universal_newlines=False, shell=None)
git.cmd                                 : 2018-04-12 13:35:45,997 DEBUG     (MainThread) Popen(['git', 'status', '-sb'], cwd=/Users/mcintosh/Pychron_dev/data/.dvc/repositories/Toba, universal_newlines=False, shell=None)
GitRepoManager                          : 2018-04-12 13:35:46,063 DEBUG     (MainThread) Smart pull ahead: 0 behind: 0
GitRepoManager                          : 2018-04-12 13:35:46,064 DEBUG     (MainThread) Up-to-date with origin
2018-04-12 13:35:47.984 python[12485:22765064] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
git.cmd                                 : 2018-04-12 13:35:50,145 DEBUG     (MainThread) Popen(['git', 'push', 'origin', 'master'], cwd=/Users/mcintosh/Pychron_dev/data/.dvc/repositories/Toba, universal_newlines=False, shell=None)

**Comment by jirhiker** [comment]
your push worked correctly.

to verify you can see the state of the "master" repository on github
https://github.com/NMGRLData/Toba
