### ISSUE TITLE
Spectrum reseting age scale when changing spectrum preferences

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1376]
When I change the Y axis (apparent age) for the spectrum, then change the prefences (specifically adding Y error to K/Ca and 40Ar), the apparent age resets to the default.

**Comment by mjz1983** [comment]
In fact, all Y axes (age, k/ca, and 40Ar) reset to default scales when changing preferences.

**Comment by jirhiker** [comment]
what mechanism are you using to modify the limits. right click and using the editor or grabbing the axis and dragging?

**Comment by mjz1983** [comment]
First, I right click on the scale then set the upper and lower limits. Then, when I click on "spectrum" in the pipeline details window, set the spectrum options, the scale changes back to the default upper and lower limits.
