### ISSUE TITLE
cell format

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1413]
I finally discovered how to read the existing format in an excel cell

The format that pychron is writing is 0.00000#

Can pychron write the format as 0.000000    to show trailing zeros?

**Comment by jirhiker** [comment]
I switched to 0.0000 cell format, but I think you will find that using 0.000# is a much better compromise.

value =0.000102 format=0.000# result=0.0001
value =0.000102 format=0.000 result=0.000
