### ISSUE TITLE
warning at startup-untracked pdf

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1430]
Last login: Sun May  6 11:52:03 on ttys000
argon143:~ argonlab2$ /Users/argonlab2/Desktop/pychron3_launcher.sh ; exit;
On branch release/py3/v18.2
Your branch is up-to-date with 'origin/release/py3/v18.2'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	H17_10.pdf

nothing added to commit but untracked files present (use "git add" to track)

**Comment by jirhiker** [comment]
not an issue. but somehow H17_10.pdf was added to source code
