### ISSUE TITLE
Age spectrum not displaying label for lower limit on auxiliary plots

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1447]
For both the K/Ca (log scale) and radiogenic yield (linear scale), the lower limit label is not displayed. This would be an space issue if labels are on the same side of the spectra, but if one is plotted on the left and another on the right, the space issue is not an issue anymore. Should this be an option. See screen shot.
![screen shot 2018-05-09 at 10 54 46 am](https://user-images.githubusercontent.com/6474471/39828538-a45f9948-5378-11e8-9817-fab59243718b.png)

**Comment by jirhiker** [comment]
it is a minor detail that in the current setup I do not have control over. Ive already spent a disproportionate time on log axes and labeling. 

There are other minor log axes issues that remain; maybe if I decide to fix them then this problem will also get fixed

**Comment by jirhiker** [comment]
Hopefully when you see the new feature im working on now you will (momentarily) forget about formatting/display issues.
