### ISSUE TITLE
Missing material label in auto generated Title

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1448]
When I select auto generate title "Sample (identifier - aliquot, material)", the material label is missing from the title. I double-checked that the material information is present in LabNumber feature of pychron.  Tested on 15L-50, NM294 M3.
![screen shot 2018-05-09 at 10 57 36 am](https://user-images.githubusercontent.com/6474471/39828737-5baf9b0c-5379-11e8-87eb-d0e101d52f56.png)

**Comment by mjz1983** [comment]
I typed it in wrong. There is a space between the aliquot and the comma. I'm using a format from the drop down window. See screenshot.
![screen shot 2018-05-09 at 1 10 17 pm](https://user-images.githubusercontent.com/6474471/39834528-813f091e-538a-11e8-8622-e6829a0df32c.png)

**Comment by jirhiker** [comment]
analyses where not saved correctly and do not contain material information. Fixing it now

**Comment by jirhiker** [comment]
LipmanDulceDikes repository is now fixed so that the sample info saved with the analysis is the same thats in the database. 

Seems like when these analyses were run the sample info was not synced correctly and so was not saved with the run.  Probably not human error.
