### ISSUE TITLE
Correct Min decay constant

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1455]
"One other item which is not helping us in comparing MS and Py is the small lambda K difference
4.463 vs 4.464. What can we do to make these match? How about adding significant figures and minimizing rounding?  from previous issue

I can change the value in MS, no problem

I was wondering more about which is the "correct" value.  Why are we stuck with 4.463 anyway?  Rounding error by Kuiper?  Didn't you and Matt communicate with Min on this?

**Comment by jirhiker** [comment]
if you look at the Min paper it lists the decay constants for the individual branches. 
add those together you get 4.463

However in the paper the total lambda_K is listed as 4.464
