### ISSUE TITLE
add updated sensitivity in recall window

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1477]
In the recall window the cell for sensitivity reads .000000000001 (1e-12) regardless of which mass spec was used in the analysis. Also, the cell does not contain units, which is typically reported in mol/fA these days.

Suggest updating this sensitivity based on recent email with Heizler (5/17/18).

Felix 4e-16 mol/fA
Jan 8e-17 mol/fA

If inclined could have 1e-16 mol/fA for Obama past analyses.

**Comment by jirhiker** [comment]
I completely agree in principal. In practice I agree but have my doubts. 

If the sensitivity values are not kept up to date then a certain degree of confusion and incorrect results will ensue.

**Comment by mjz1983** [comment]
How best to deal with this? Right now, it is basically unknown to anyone except the regular users (you and Matt). Or maybe I'm the only one in the dark. 

Do you think there should be a regular interval at which sensitivity is calculated (e.g., first Monday of every month) and updated? Can pychron keep a running calculation based on prior analyses?

**Comment by wcmcintosh** [comment]
I see that sensitivity for recent Jan analyses is recalled as 1e-17.  Should this be 8 e-17?
