### ISSUE TITLE
Table issues

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1492]
Tables working well with grouping and subgrouping, and requested summary ages are being calculated

A few display issues remain:  
Human table 
- [x]  could mswd be added to weighted mean and plateau display lines, as MSWD=x.xxx after n=x/y?
- [x] could sensitivity be formatted in scientific notation?
- [x] ~~could vertical cell border between columns b and C be removed?~~
- [x] could weighted mean have 1 vs 2 sigma option (option fine in summary table?
- [x] could %39 be included for omitted steps?

Summary table
- [x] for mean ages,  n column currently displays nt.  Could it display n/nt, like in the human table
- [x] for a=1,s>1 subgroups, reported n=1 and reported MSWD=0.  Human table has correct values

**Comment by jirhiker** [comment]
give mean an example excel file with the changes you want highlighted

**Comment by wcmcintosh** [comment]
here is highlighted example, except for 1/2 sigma option for human table configuration
[1.xlsx](https://github.com/NMGRL/pychron/files/2028464/1.xlsx)

**Comment by wcmcintosh** [comment]
summary table changes tested - OK
1 vs 2 sigma tested  - OK
other items have small problems, see attached excel file
[3.xlsx](https://github.com/NMGRL/pychron/files/2032075/3.xlsx)

**Comment by wcmcintosh** [comment]
tested - all issues in 3.xls fixed except one miserable cell border.  see "border gap" in 4.xls
[4.xlsx](https://github.com/NMGRL/pychron/files/2032375/4.xlsx)

**Comment by wcmcintosh** [comment]
I should have noticed sooner, but weighted-mean age errors in tables are not multiplied by sqrt-mswd, leading to  table/figure error mismatch.  
Other table features inc subgrouping etc. working perfectly.

**Comment by jirhiker** [comment]
controlling the subgrouping error kind was never requested

**Comment by wcmcintosh** [comment]
Like I say, I should have noticed and requested sooner.  My mistake.

**Comment by wcmcintosh** [comment]
Attached excel file has 4 high-lighted small problems.  Thanks.
[9.xlsx](https://github.com/NMGRL/pychron/files/2036433/9.xlsx)

**Comment by wcmcintosh** [comment]
All four problems resolved.  Ready to close.
