### ISSUE TITLE
ideogram request

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1501]
In cases where an ideogram lacks data, e.g. a subgroup mean without 39Ar or %rad values, could the ideogram just not plot the points rather than plot them as 0 ± 0?  
In the future we may be able to plot these points as mean values, but leaving them off the ideogram may make the most sense for now.

**Comment by jirhiker** [comment]
in the future subgroups will have mean values for 39Ar, %rad, etc... 

Its up to the user to setup the aux plots with logical selections. 

Implicitly removing the analyses is bad practice, lacks clarity and not the correct solution to the problem

**Comment by jirhiker** [comment]
see #1499
