### ISSUE TITLE
Table issues

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1522]
Summary table showing 0 ± 0 for mean ages.
IR998 data

**Comment by wcmcintosh** [comment]
I can replicate with IR998 data
See attached table
[1.xlsx](https://github.com/NMGRL/pychron/files/2051029/1.xlsx)

**Comment by jirhiker** [comment]
In the future this is a case where more testing would be helpful. 

does it work for Type I,II,III data

Saying IR998 is too ambiguous. When I tested one type III data set it working fine.

**Comment by jirhiker** [comment]
still can not replicate

[Untitled-006.xlsx](https://github.com/NMGRL/pychron/files/2051087/Untitled-006.xlsx)
