### ISSUE TITLE
Standardize 39Ar units

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1527]
Ideally fA or moles could be chosen for 39A units.  
Tables are currently fA, but ideograms are moles.

Could we temporarily standardized of fA, so tables and figures match?  

Thanks

**Comment by wcmcintosh** [comment]
That's great, but I haven't yet figured out how to switch

**Comment by wcmcintosh** [comment]
I hit the bomb.  Other than the Pycharm message below, I don't see an effect.  Should the dropdown offer two 39Ar options?

**Comment by wcmcintosh** [comment]
IdeogramOptionsManager                  : 2018-05-30 09:40:33,980 DEBUG     (MainThread) set factory default

**Comment by jirhiker** [comment]
when i hit the bomb the options are cleared and the aux plots needed to be repopulated. 

There should be Signal 39Ar and Mol 39Ar

**Comment by wcmcintosh** [comment]
I rebombed after last update, but no luck.  Heading into town now.

**Comment by jirhiker** [comment]
setting the factory defaults only works for the default options "screen" and "presentation"

If not using either of those you will need to save a new options set

**Comment by wcmcintosh** [comment]
mol39/fA39 working perfectly in figures. Ready to close.
