### ISSUE TITLE
omitted steps not included in integrated age

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1533]
"Lastly, the spectrum figure for 65773 labels the mean age as "plateau=" rather than "weighted mean=". The numbers are correct, but gas is <50%, so not a plateau."
don't know about this but should be simple

The integrated age is n=4, is therefore not including omitted steps, which should be included.  I wonder if the plateau criteria are not being applied to all the steps, just the non-omitted steps.

Opened as new issue.  Was in #1532

**Comment by jirhiker** [comment]
"including omitted steps, which should be included" Why should omitted steps be included. Whats the point of omitting it omitting doesn't mean "don't include"
