### ISSUE TITLE
auto/manual for nodes

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1536]
Any issue that we talked about, that I would like to formalize:

Could we add to the right click menu and auto/manual switch for user interaction pipeline nodes.
Ideally, switching to auto would lock in and persist the current configuration, and color-flag the auto node.  

Big deal or not big deal?

**Comment by jirhiker** [comment]
Use Disable Auto Configure/ Enable Auto Configure

**Comment by wcmcintosh** [comment]
Disable Auto Configure/ Enable Auto Configure seems to work perfectly.  Ready to close.
