### ISSUE TITLE
Right click set invalid not working from ideogram

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1540]
Right click set invalid not working from ideogram plot, working fine from tag icon

**Comment by jirhiker** [comment]
not working is way too ambiguous of a description. 
In this case it doesn't really matter but as a "tester" i would like you to provide more information.

How is it not working. Is is specific to single group ideograms or multi-group ideograms. What type of analyses does it not work.

More rigorous nomenclature would also help.  Tag icon simple refers to an image. I think you mean the "Set Tag" Toolbar action.
