### ISSUE TITLE
extraneous sample on tag list

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1541]
This problem has been around for a long time (months)?
In some cases, when clicking on analyses on a graph, then pushing the tag button, the list of analyses to be tagged include the clicked analyses, plus one undesired analysis from the previous dataset. Example below.   Clicked two data points in 66270 ideogram, then tag button.  The list in the tag window includes 66269-02A from the previous dataset.

[3.pdf](https://github.com/NMGRL/pychron/files/2064438/3.pdf)

**Comment by jirhiker** [comment]
In order to properly test this you will need to define "In some cases" much more rigorously.

What are the exact steps taken that produce the behavior, otherwise the chance of a false positive "Tested OK" is very high.
