### ISSUE TITLE
Table group means

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1550]
Requesting that plateau ages be used are group means in cases where aliquots=1, steps>1 and plateau criteria is met.  Goal: table group algorithms consistent with figure and subgroup algorithms.

**Comment by jirhiker** [comment]
not yet totally addressed  but latest change makes it so that the subgroup settings are used as the group settings when nsubgroups ==1

**Comment by wcmcintosh** [comment]
I believe that this is working fine now.  Ready to close.
