### ISSUE TITLE
human table - blank lines between analyses

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1562]
Could we add a blank line between analyses in the human table.  Current version lacks same, see example.
[1.xlsx](https://github.com/NMGRL/pychron/files/2096225/1.xlsx)

**Comment by jirhiker** [comment]
Where do yo want blank lines added?

**Comment by wcmcintosh** [comment]
A blank line before each "Sample" line to separate different groups would be perfect.

**Comment by wcmcintosh** [comment]
Problem solved. 
Ready to close.
