### ISSUE TITLE
k20= request, not urgent, 

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1564]
The mean K2O value and label current occupy 2 columns,  Could K2O=xxx.x.x be combined  in the same fashion as mswd=xxx.xxx, so that K2O= vanishes when K2O column is hidden?

**Comment by jirhiker** [comment]
It but you'd lose the ability to format the k2o value in excel because the cell goes from a number cell to a text ceell

**Comment by wcmcintosh** [comment]
K2O working fine now.  Ready to close.
