### ISSUE TITLE
total integrated age problem - not show-stopper

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1565]
See per attached table.  Total integrated age only appropriate for single-aliquot groups or subgroups.  Currently included with fusion data where aliquots > 1. 

[2.xlsx](https://github.com/NMGRL/pychron/files/2096331/2.xlsx)

**Comment by jirhiker** [comment]
The user has control of whether the integrated age is display as part of the summary rows

**Comment by wcmcintosh** [comment]
"The user has control of whether the integrated age is display as part of the summary rows"

I haven't tested your change yet, but in a Type 3 data set, wouldn't it make sense to show integrated age for single-aliquot step-heat data, but not formulti-aliquot fusion data (inappropriate statistic)

**Comment by jirhiker** [comment]
simply stating that the user has control.

"I haven't tested your change yet, but in a Type 3 data set, wouldn't it make sense to show integrated age for single-aliquot step-heat data, but not formulti-aliquot fusion data (inappropriate statistic)" I agree in this case but this is another example where we fundamentally disagree. 

Its not up to the developer to define whats a sensible use of statistics, its up to the user to understand what they are asking of the application.

**Comment by wcmcintosh** [comment]
Total integrated seems to be being applied correctly to step heating data, and not to fusion data.  All working well. Ready to close.
