### ISSUE TITLE
Excel node configuration - small issues

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1579]
In Excel node configuration:  
K20 column not hiding when unchecked
K/Ca choice of error methods no longer used here

**Comment by wcmcintosh** [comment]
%39Ar also column not hiding when unchecked

**Comment by jirhiker** [comment]
proper testing would indicated that no columns are being hidden

**Comment by wcmcintosh** [comment]
Columns correctly hidden.  Ready to close.
