### ISSUE TITLE
Subgroup means not displayed when there is only one subgroup 

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1582]
Subgroup means not displayed when there is only one subgroup in a group.  Grouping is fine and %39 correctly calculated.

For groups with more than one subgroup, all subgroup means are correctly displayed.

See attached Excel spreadsheet.

\[121.xlsx](https://github.com/NMGRL/pychron/files/2120242/121.xlsx)

**Comment by wcmcintosh** [comment]
Single subgroups correctly displaying means and errors.  All OK except for very minor formatting issue - an extra table-wide cell border is added between single subgroups and the subgroup means.  Does not occur for multiple subgroups.  Attached excel spreadsheet shows extra line.

[4.xlsx](https://github.com/NMGRL/pychron/files/2128628/4.xlsx)

**Comment by jirhiker** [comment]
fixed the previous specific issue. Likely broke for other types of data

**Comment by wcmcintosh** [comment]
Formatting problem all fixed.  Cell borders all OK I think.  I'll try more testing of single aliquot datasets.
