### ISSUE TITLE
Sample table configuration - minor problem, not showstopper

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1584]
If configure sample table is selected from the browser, it opens behind the browser window.  It remains inactive unless the browser window is closed, then it can be accessed.  

In contrast, configuring the analysis table opens in front of the browser window, and is accessible without closing the browser window.

**Comment by jirhiker** [comment]
this only occurs when running a pipeline. Not on recall

**Comment by wcmcintosh** [comment]
Configuration accessible in  either recall or pipeline now.  Ready to close.
