### ISSUE TITLE
Spurious analyses

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1587]
Small problem, but analyses 19211-02, 03, 04, 05, 06, 07, come up as belonging to  NM-274G, but they don't belong there, and also don't seem to really exist (not found in repository).  I tried to mark them as invalid, but can't since they are not in the repository.  Can they be removed from the database?

**Comment by jirhiker** [comment]
analyses 19211-01 to 19211-07 marked as invalid
