### ISSUE TITLE
IC factor options configuration

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1588]
When running an IC factor pipeline, the IC factor options configuration remembers the name of the last used configuration, but the actual details in some cases (e.g. after program restart) do not match the configuration until the user toggles to another configuration and back again.  This behavior seems different than that of most other configuration windows.  I'm wondering why.

**Comment by jirhiker** [comment]
Its the problem that its very difficult to intuit whether the user wants to use the defaults or the previous configuration

**Comment by jirhiker** [comment]
If you except no defaults for the IC factor pipeline template then it would probably work much better

**Comment by wcmcintosh** [comment]
The current model is kind of half of each, previous name but default parameters.

**Comment by jirhiker** [comment]
yep

**Comment by wcmcintosh** [comment]
Did you make a change to no defaults, use persisted value?  I haven't tested this yet but can.

**Comment by jirhiker** [comment]
it uses the defaults if the "Default" configuration is selected otherwise it should use the persisted values

**Comment by wcmcintosh** [comment]
Working well with persisted values.  Ready to close.
