### ISSUE TITLE
subgroup mean error type 

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1592]
subgroup mean for plateau ages reporting SEM error, regardless of what is selected configuration.

SEM/MSWD, SEM, SD all give SEM value

**Comment by wcmcintosh** [comment]
Spectrum pipeline handles error choice correctly

**Comment by wcmcintosh** [comment]
Likewise, group plateau using arithmetic mean ± SD instead of selection.  All a consequence of fixing the single group format issue?

**Comment by wcmcintosh** [comment]
Possibly related issue in Spectrum pipeline,  Spectrum options: spectrum  allows selection of error type for weighted-mean age.  Error for weighted-mean age is SEM regardless of selection.  Error type for plateau correctly responds to choice.

**Comment by wcmcintosh** [comment]
Subgroup plateau ages now reporting SEM/mswd errors correctly.
Subgroup weighted mean ages still reporting SEM errors.

**Comment by jirhiker** [comment]
"Subgroup weighted mean ages still reporting SEM errors." could not reproduce

**Comment by wcmcintosh** [comment]
Same for spectra - plateau age errors are SEM/MSWD
Weighted mean errors SEM.

**Comment by jirhiker** [comment]
The behavior of the spectrum is not necessarily related to the behavior of the subgroups

**Comment by wcmcintosh** [comment]
I wasn't sure but thought it a possibility.

**Comment by wcmcintosh** [comment]
No longer a problem.  I think that all error kind selections are now correct. Ready to close.
