### ISSUE TITLE
MSWD on weighted mean for spectra

### ISSUE THREAD

**Issue by nelsiverson** [NMGRL/pychron#1604]
Currently no MSWD reported for weighted mean age for a spectra. It shows up for the plateau age but not when you force a plateau (i.e. weighted mean age)

**Comment by wcmcintosh** [comment]
Having the option to add "n=xxx" would also be a good addition to weighted mean age, analogous to the plateau age display.

**Comment by wcmcintosh** [comment]
Working great.  Ready to close.
