### ISSUE TITLE
Issues with using no subgrouping

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1633]
***error occurred when clicking on any of the option nodes.

active branch=release/py3/v18.2

active analyses=66526-01,66526-02,66526-03,66526-04,66527-01,66527-02,66527-03,66527-04,66528-01,66528-02,66528-03,66528-04,66529-01,66529-02,66529-03,66529-04,66530-01,66530-02,66530-03,66530-04,66531-01,66531-02,66531-03,66531-04,66532-01,66532-02,66532-03,66532-04,66533-01,66533-02,66533-03,66533-04,66526-05,66526-06,66526-07,66526-08,66526-09,66526-10,66526-11,66526-12,66526-13,66526-14,66526-15,66526-16,66526-17,66527-05,66527-06,66527-07,66527-08,66527-09,66527-10,66527-11,66527-12,66527-13,66527-14,66527-15,66527-16,66527-17,66528-05,66528-06,66528-07,66528-08,66528-09,66528-10,66528-11,66528-12,66528-13,66528-14,66528-15,66528-16,66528-17,66529-05,66529-06,66529-07,66529-08,66529-09,66529-10,66529-11,66529-12,66529-13,66529-14,66529-15,66529-16,66529-17,66530-05,66530-06,66530-07,66530-08,66530-09,66530-10,66530-11,66530-12,66530-13,66530-14,66530-15,66530-16,66530-17,66531-05,66531-06,66531-07,66531-08,66531-09,66531-10,66531-11,66531-12,66531-13,66531-14,66531-15,66531-16,66531-17,66532-05,66532-06,66532-07,66532-08,66532-09,66532-10,66532-11,66532-12,66532-13,66532-14,66532-15,66532-16,66532-17,66533-05,66533-06,66533-07,66533-08,66533-09,66533-10,66533-11,66533-12,66533-13,66533-14,66533-15,66533-16,66533-17,66533-18

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/nodes/grouping.py", line 146, in _by_key_changed
    self._run(self._cached_items)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/nodes/grouping.py", line 62, in _run
    unks = getattr(state, self.analysis_kind)
AttributeError: 'TraitListObject' object has no attribute 'unknowns'
-

**Comment by wcmcintosh** [comment]
grouping A-OK.  Ready to close.
