### ISSUE TITLE
IC Factor Pipeline - Unnecessary reference list?

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1642]
When using the IC factor in the pipeline, the user is prompted by a window that includes the option to find numerous references (blank unknowns, blank airs, etc...).

Most of these are not relevant. The only two reference options that I think the user should be prompted to find when dealing with IC factors are  airs and cocktails, right?. Or am I missing something.

I'm trying to think about simplifying the selection process and not overloading users with too many options.

**Comment by jirhiker** [comment]
Im slightly sympathetic to the idea of simplifying the selection process... however as the developer its not up to me to define which analyses can be used for IC factor fitting. 

therefore if you want to limit the choices it must be configurable, which adds another layer of complexity.
