### ISSUE TITLE
bracketing interpolation issue

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1643]
When fitting blanks with bracketing interpolation, blanks that are not bracketing the unknowns are impacting the fit of the unknowns. See the attached screen shots. When I remove a blank from many hours before the unknowns where analyzed, the omitted blank appears to remove on the unknown blank values. Maybe just a graphical issue.
![screen shot 2018-08-29 at 10 16 58 am](https://user-images.githubusercontent.com/6482990/44801591-b078d680-ab76-11e8-9f59-c05b2781895e.png)
![screen shot 2018-08-29 at 10 17 10 am](https://user-images.githubusercontent.com/6482990/44801593-b078d680-ab76-11e8-90e9-e84ba8136c99.png)

**Comment by jirhiker** [comment]
what happens when you select the second green point instead of the first one?
if you select the second green point does the second black point go white or still the first point?

This is just a graphical issue and I dont think it has an downstream consequences.
