### ISSUE TITLE
Age spectrum plotting problem

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1666]
When plotting a series of Cocktails as an age spectrum pychron is crashing. I tried using the pipeline (plot>spectrum>) and after selecting my 3 cocktail analyses the program crashed. I tried Data>spectrum and after selecting my 3 cocktail analyses it appeared to then try to plot a much larger set of cocktail analyses, only to crash.

**Comment by jirhiker** [comment]
the issue is with trying to plot values in negative log space. changing K/Ca scale to linear resolved the problem
