### ISSUE TITLE
Missing metadata in recall window

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1668]
Much of the metadata is missing from the recall window, such as device, position (in the laser tray, etc...

![screen shot 2018-10-29 at 8 20 30 am](https://user-images.githubusercontent.com/6474471/47656143-23410680-db54-11e8-8eb7-8c873aa8321f.png)

**Comment by jirhiker** [comment]
this analysis has not extraction file in the repository. exact cause is not clear. only issue identified was that pychron was trying to save 209-221 has a position to the MeasuredPositionTbl which causes an exception. however the only relevant experiment file found has blanks with position 209-221 but not any of the 66610 analyses.
