### ISSUE TITLE
Selection baseline isoevo fits for Jan

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1687]
When fitting isotopic evolutions there does not appear to be a ability to fit baselines for L2 (Ar37) and CDD (Ar36).

L2(CDD) option appears to be a setup or nomenclature for Felix.

=

![screen shot 2018-11-23 at 11 16 27 am](https://user-images.githubusercontent.com/6474471/48956626-4ff8fb80-ef11-11e8-81b2-d31228b4cc35.png)

**Comment by jirhiker** [comment]
the names in the drop down are generated from the isotopes/detectors of  the first select analysis. So potentially the first analysis you selected was run on felix? Otherwise its a bug
