### ISSUE TITLE
Add option to move Age and Error

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1714]
Suggest option to move Age ± 2sigma and Error Envelope ± 2sigma. Make similar to click and drag the plateau or weighted mean information.
![screen shot 2019-03-04 at 10 23 57 am](https://user-images.githubusercontent.com/6474471/53750741-d6559f80-3e67-11e9-98d0-80b520cd2bf3.png)

**Comment by jirhiker** [comment]
I added this feature, however if you move the label, then "tweak preferences" the label will go back to the upper left. Im not going to make it so that pychron remembers where the label was moved to any time soon
