### ISSUE TITLE
Integrated age not calculated/displayed correctly

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1717]
Integrated age for TinajaDikes (1 and 2) as displayed on spectrum is not correct. Compare pdf to excel data table.
[TinajaDikes.xlsx](https://github.com/NMGRL/pychron/files/2932105/TinajaDikes.xlsx)
[TinajaDikesSpectra_1column.pdf](https://github.com/NMGRL/pychron/files/2932106/TinajaDikesSpectra_1column.pdf)

**Comment by jirhiker** [comment]
likely has to do with how the weighting for integrated age calculation is being done and that you do not have it set the same for the figure and the table.

**Comment by mjz1983** [comment]
Seems like a pretty major error not explaind by weighting factors. Check out the age differences (~23 Ma vs. >100Ma)

Z

Matthew Zimmerer
Field Geologist II
NM Bureau of Geology
801 Leroy Pl
Socorro, NM 87801
matthew.zimmerer@nmt.edu
575.835.5114
www.mattzphotography.com

**Comment by jirhiker** [comment]
k. you might be right

**Comment by jirhiker** [comment]
k. the problem is definitely related to weighting. When you make the spectrum make sure to set the weighting to volume or variance. There currently is a bug in the integrated age calculation if the weighing is set to `---`
