### ISSUE TITLE
Spectra steps plotting with different colors

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1718]
When plotting a gray spectrum, some steps appear lt gray and some appear mod. gray. Or maybe it is a difference is the opaque setting. Seems reproducible regardless of color.
![screen shot 2019-03-05 at 10 49 56 am](https://user-images.githubusercontent.com/6474471/53826047-ee472500-3f34-11e9-8574-39d8d531d660.png)
![screen shot 2019-03-05 at 10 52 33 am](https://user-images.githubusercontent.com/6474471/53826052-f30bd900-3f34-11e9-9a69-1fe770a1fea6.png)

**Comment by jirhiker** [comment]
this is a consequence of a WiscAr request but its also a little bizarre. 

in the Spectrum options under "Integrated Age" there is a option called "Include omitted"  Deselect that

**Comment by mjz1983** [comment]
Toggling "include omitted" has no impact. Spectrum still plots with different opaque settings regardless of whether the option is toggled.

**Comment by jirhiker** [comment]
sorry wrong option. 
Try "Dim No Plateau"
