### ISSUE TITLE
Change Ar40/Ar36 to 40Ar/36Ar in isochron display

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1721]
When displaying results of an isochron analysis the y-intercept is now listed as Ar40/Ar36. Suggest changing to 40Ar/36Ar (similar to the y-axis label). Superscript the 40 and 36.

![Screen Shot 2019-03-13 at 1 39 21 PM](https://user-images.githubusercontent.com/6474471/54309516-ecfda400-4595-11e9-9a08-5d4e0d1d5ea5.png)

**Comment by jirhiker** [comment]
Ugh. I was hoping the would slip thru. The way Im doing the sub/superscripts for the axes is a bit of a hack and I don't think we easily translate to the results display.

Quick question. Did you manually add that PLUS-MINUS symbol?

**Comment by mjz1983** [comment]
Yes to the manual entry
