### ISSUE TITLE
Spectrum/isochron yields blank output

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1755]
for 66853-01, spectrum and isochron both working, but  spectrum/isochron yields blank output

**Comment by jirhiker** [comment]
Make sure the Spectrum/Isochron options are properly configured
![Screen Shot 2019-06-05 at 4 08 09 PM](https://user-images.githubusercontent.com/2035568/58994074-94146500-87ac-11e9-8bbd-01dd39005468.png)
![Screen Shot 2019-06-05 at 4 09 43 PM](https://user-images.githubusercontent.com/2035568/58994075-94146500-87ac-11e9-8bf9-45ec2170bdcd.png)
