### ISSUE TITLE
Tweak adding labels to age spectrum

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1768]
When adding labels (step or power/temp) to the age spectrum, the labels appear on the spectrum, K/Ca, and radiogenic yield plots (and presumably all aux. plots). Suggest adding only to the age spectrum. Adding labels to the aux. plots produces a "busy" plot. Or, provide option to only provide labels to the age spectrum itself.

**Comment by jirhiker** [comment]
already configurable which aux plot the labels are displayed. 
![Screen Shot 2019-06-17 at 11 42 50 AM](https://user-images.githubusercontent.com/2035568/59624840-137f2e00-90f5-11e9-8e39-5aac24164ab5.png)
