### ISSUE TITLE
Standardize list order under File and View

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1770]
The order of items under File and View is different for both pyExperiment on for the diode/Felix and CO2/Jan. For example, the first three items under File on the diode are open ex., open current ex., and open last ex. The first three items under File on the CO2 are open peak hops, open script, and open visual pyscript. Same issue exists for items under View. Suggest standardizing this format to enhance the user experiment and helping students learn the function of pyExp.

**Comment by jirhiker** [comment]
What is displayed in the menus is configurable via "Help/Edit UI" and what plugins are enabled for a given application. 

Ill look a little into the ordering but for the most part what is displayed is up to the user
