### ISSUE TITLE
could SEM + sqrt MSWD fit option be added to flux fit calculations?

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1785]
could SEM + sqrt MSWD fit option be added to flux fit calculations?

**Comment by jirhiker** [comment]
is that not already an option

![Screen Shot 2019-07-18 at 9 28 22 AM](https://user-images.githubusercontent.com/2035568/61470473-693a3680-a93e-11e9-9a7a-d7245de0564e.png)
