### ISSUE TITLE
subgroup/sorting problem

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1786]
Chris's sample 66788 was run in two steps, first without a step label, and second labelled B.  Bs were run one day after the initial step.  We want to use subgrouping to plot the data.
However, when we sort the data, and then display it as a spectrum, the individual steps are labelled in the correct order, but the data do not correspond to the correct labelled step.  Subgrouping is having similar problems.  Perhaps, this may all be caused by the lack of "A" labels on the first steps?  In any case, Pychron seems to be correctly sorting only parts of the data, such that data and L# are not correctly matched.

**Comment by jirhiker** [comment]
could not replicate issue with plotting a spectrum. 

making a subgrouped ideogram does not appear to work for this data currently. Addressing the issue now
![Screen Shot 2019-07-18 at 11 06 03 AM](https://user-images.githubusercontent.com/2035568/61477433-752cf500-a94c-11e9-9339-f57272ec5995.png)
