### ISSUE TITLE
problems plotting spectra from Jan-pychron

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1788]
When plotting figures in pyExp on Jan, the plots do not show numerical values. Also, there are problems with ± and sigma symbols.

Z
<img width="1048" alt="Screen Shot 2019-07-19 at 8 06 20 AM" src="https://user-images.githubusercontent.com/6474471/61541199-7584c900-a9fc-11e9-9f94-89c82fd68a94.png">

**Comment by jirhiker** [comment]
try changing the font. This is a computer specific font issue that is unresolved

**Comment by mjz1983** [comment]
Problem with font is consistent with all available fonts. Also, for clarification, the font issue is when viewing it in pyChron, not in Adobe Illustrator

**Comment by jirhiker** [comment]
Copy the viewing in pychron. Thats what I thought

When you change the font does the displayed font actually change or is it always that mono-spaced 
"typewriter-y" font

**Comment by mjz1983** [comment]
Nope. It actually changes the font.

**Comment by jirhiker** [comment]
on thing to try is clearing the font cache.  

rename to $HOME/.enthought/kiva/fontList.cache to $HOME/.enthought/kiva/~fontList.cache
