### ISSUE TITLE
Pychron not plotting data from the last two days

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1799]
I can not plot the blanks and unknowns from the last couple of days in pychron. However they plot in MassSpec

**Comment by jirhiker** [comment]
the analyses are accurately recorded in the database and repository. The issue is that the data
collection computer is not automatically sharing the new analyses.

this appears to be something to do with credentials on the dc comp? 

Add a startup test to github plugin that checks credentials
