### ISSUE TITLE
labelling analyses not working

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1822]
When toggling "Labels" for Analyses on CSV ideogram, the plot does not update. Analysis points remain un-labelled with RUN ID name. Only a problem with CSV ideogram. Works fine for ideogram from database.

**Comment by jirhiker** [comment]
You need to specify the attribute to use to label the points. 
![Screen Shot 2019-09-11 at 10 25 57 AM](https://user-images.githubusercontent.com/2035568/64715919-93abfa00-d47e-11e9-9fd9-f81bb4a320b4.png)

**Comment by mjz1983** [comment]
Labelling points not working, regardless of whether using predefined labels or attempting to creating unique labels. Label box is tagged. See screenshoot. Maybe user is missing something???

![Screen Shot 2019-11-25 at 10 44 41 AM](https://user-images.githubusercontent.com/6474471/69564662-a6f43f00-0f70-11ea-980d-ef0d875b3bd3.png)

**Comment by jirhiker** [comment]
you need to turn labeling on per aux plot

**Comment by mjz1983** [comment]
OK.
