### ISSUE TITLE
Blank Unknown not showing up with a load number

### ISSUE THREAD

**Issue by nelsiverson** [NMGRL/pychron#1831]
I am trying to recall blanks and they are not showing up with their load number. The time stamp works. 
C0077 was the last load that has Blanks associated with the load numbers

![Screen Shot 2019-10-30 at 2 35 47 PM](https://user-images.githubusercontent.com/33048412/67897009-22ee9900-fb23-11e9-8120-9d3e3fba742d.png)

**Comment by jirhiker** [comment]
all future blank_unknowns now should be associated with the load. i did not retroactively fix loads 78-81
