### ISSUE TITLE
Changing appearance of isochron inset

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1838]
When adding an isochron inset, there are currently no options to change the appearance of the inset plot. For example, changing scale, font, adding/removing labels.

Only current option is to change the size of the inset.

**Comment by jirhiker** [comment]
added some editability to the isochron inset. 
Please explicitly enumerate the aspects you'd like to control

**Comment by mjz1983** [comment]
Please add error ellipses to inset. Please add label axis. Font and font size currently not adjusting.
