### ISSUE TITLE
Add additional significant figures to IC error component in recall window

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1839]
When viewing the IC error component in the recall window, the error component is only reported to one significant figure. Suggested adding additional significant figures (perhaps similar to that of the IC value) so that one can asses this error value.
![Screen Shot 2019-11-25 at 4 34 30 PM](https://user-images.githubusercontent.com/6474471/69587189-23ebdc80-0fa2-11ea-97b5-4d90e00ed58a.png)

**Comment by jirhiker** [comment]
that column does not refer to the error contribution to the age from the IC factor.
It is the error contribution to the age from the Isotope.  To see error contribution from ic factor see "Error Components" tab
