### ISSUE TITLE
Ideogram Error not updating

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1840]
When toggling the four different error options for Uncertainty Calculations for ideogram (e.g., include decay constant), the weighted mean error on the ideogram plot does not update. This is true for all four Uncertainty options (Positions error, include in mean, include irradiation error, include decay error).

**Comment by jirhiker** [comment]
after some cursory testing I agree on` include decay error` and `include irradiation error`.

`Position error` may or may not work but it's only going to work if the Js were calculated with a position error. 

`Include in mean` was working for me

**Comment by jirhiker** [comment]
fixed `include_decay_error` you should verify the uncertainty is being incorporated correctly tho

**Comment by mjz1983** [comment]
What is the "correct way" to incorporate the decay constant?

**Comment by jirhiker** [comment]
idk
