### ISSUE TITLE
Inset isochron not updating when toggling points

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1841]
Currently not able to toggle points on the inset isochron. Would be nice to be able to remove points on the inset ideogram simply by clicking the points. Perhaps even better would be to remove points on inset plot by having the two plots (main plot and inset plot) co-registered, so that removing/tagging points on the main plots updates the inset plot.

**Comment by jirhiker** [comment]
ok. the point of the inset is to show all the data thats why its not editable. 

here are the updates I will make
1. removing a point for the main plot should remove from the inset
2. add option to link omit status between both plots
