### ISSUE TITLE
Missing data for cocktails

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1846]
![Screen Shot 2019-12-04 at 12 53 27 PM](https://user-images.githubusercontent.com/6474471/70176143-2b437200-1695-11ea-972c-a1f2255b8af1.png)

**Comment by mjz1983** [comment]
For what it's worth, the data shows up in Mass Spec

**Comment by jirhiker** [comment]
latest cocktails fixed.

cause for missing data is unknown
