### ISSUE TITLE
Error calculation for isochron

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1860]
Working with different error calculation methods for isochrons. Can you check the method of SEM*Square Root of MSWD when MSWD>1? 

Try 18L-6 (67292). SEM only error is 0.026 Ma and the MSWD is 51.93. Using the "if MSWD >1, then use SEM*sq rt of MSWD, this should yield an error of 0.187 Ma. Pychron calculation is an error of 0.647. See attached plots.
![Screen Shot 2019-12-17 at 9 12 42 AM](https://user-images.githubusercontent.com/6474471/71015731-596f7b80-20b1-11ea-9ebc-3d4cd460796d.png)
![Screen Shot 2019-12-17 at 9 13 19 AM](https://user-images.githubusercontent.com/6474471/71015733-596f7b80-20b1-11ea-8e99-456679c5616c.png)

**Comment by jirhiker** [comment]
ok. ill look into it. likely a bug
