### ISSUE TITLE
Identify Peaks

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1866]
How can a user turn on the Sparrow datasource plugin in order to identify peaks on an ideogram.

Also, small typo in warning for identify peaks. "At least one" vs. "At least on".
![Screen Shot 2020-01-06 at 10 03 21 AM](https://user-images.githubusercontent.com/6474471/71834315-314db980-306c-11ea-9911-670f1b00c1bb.png)

**Comment by jirhiker** [comment]
To turn on plugins use Help/Edit Initialization.

Unfortunately I don't think thats gonna get you very far only because there are no "Interpreted Ages" in our Sparrow database. We'll need to discuss setting up our Sparrow db and setting interpreted ages as a group
