### ISSUE TITLE
Isochron error env. not correct

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1880]
Error envelope for isochrons does not match numerical value. See attached screenshot. 40/46 ration is 287.7±1.4, yet the graphical representation shows a large error that should be large enough to overlap with 295.5. Method is New York ± SE. Same results using York ± SE
![Screen Shot 2020-02-11 at 10 17 04 AM](https://user-images.githubusercontent.com/6474471/74261050-cf5e2080-4cb7-11ea-9c3c-fc8483624458.png)

**Comment by jirhiker** [comment]
do not display the error envelope. The error envelope and the intercept errors are directly related and will never match
