### ISSUE TITLE
JanAuto3SigBase bug

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1910]
When fitting isotopic evolutions for Jan, the JanAuto3SigBase does not include L2 or CDD fits. The baselines cannot be added and are not included in the drop down menu. Interestingly, if you select the Fit IsoEvo node in the Iso Evo pipeline without any populated analyses, the JanAuto3SigBase includes L2 and CDD fits, but these cannot be edited. See screenshots. Somewhat hard to explain. Hope this is clear.
![Screen Shot 2020-08-18 at 4 54 24 PM](https://user-images.githubusercontent.com/6474471/90573677-3a5f4700-e174-11ea-9d18-3517b3f89aa7.png)
![Screen Shot 2020-08-18 at 4 55 24 PM](https://user-images.githubusercontent.com/6474471/90573678-3a5f4700-e174-11ea-8288-37c649176419.png)

**Comment by jirhiker** [comment]
What is available in the drop down is based on the analyses. in the case where L2 and CDD don't show up what analyses are you selecting

**Comment by mjz1983** [comment]
User error. Was plotting Felix data and accidentally used Jan set-u.
