### ISSUE TITLE
Tables for step-heat analyses

### ISSUE THREAD

**Issue by cburrill** [NMGRL/pychron#1936]
This is a list of bugs associated with making tables using the Table>Grouped Analyses pipeline for step-heat analyses. The bugs are pointed out in the attached spreadsheets.

**To Reproduce**
What was done:
Table>Grouped Analyses
Selected analyses from a load (in this case DOO68) and put analyses in order of Run ID, clicked ok
Selected No Grouping
Used most default settings for Review (changed some sig. fig. options and age units)

**Bug 1: The heating steps are not in order in the “Table X Unknowns”.**
It doesn’t matter whether the run IDs are sorted or not when selecting the analyses for the table.
It doesn’t matter what combination of boxes are checked in XLS Options under Main tab >Sorting, whether just one or two or all three.
I also tried this by selecting Grouping by Identifier and Sample – same issue.
Also tried just putting 1 sample into a table to see if multiple samples were causing the issue but the steps are still out of order for 1 sample.
The steps are in order in the “Unknowns (machine)” tab of the spreadsheet.

**Bug 2:** When the K/Cl is not selected in XLS options, the data still shows up in the “Table X Unknowns” but with an error heading (+/- 1 sigma).

**Bug 3a:** The Cum %39Ar column isn’t populated in the “Table X Unknowns” when there is no plateau age, but this information is needed either way. 

Bug 3b: Similarly, the %39Ar isn’t populated in the Table X Summary ” when there is no plateau age, but this information is needed either way. 

Bug 4: When you select or input the significant figures you sometimes get a different amount of significant figures in the table. For example in the Summary tab, we asked for 2 sig figs of %39Ar and there are 5 sig figs.

Bug 5: In XLS table options, asked for ages with 1 sigma and table shows 2 sigma.

Bug 6: In XLS Table options in the Unknowns tab, in the Significant Figures area, there is a field for %40Ar* but this doesn’t show up in the table x unknowns. There is a column “%40Ar” which might be just missing the asterisk. (see picture and table)

**To Reproduce**
What was done:
Tables>Grouped Analyses
Selected analyses from a load (in this case DOO68) and put analyses in order of Run ID
Selected group by Step
Used most default settings for Review (changed some sig. fig. options and age units)

Bug 7: Though multiple steps from different samples are grouped together, the sample names are not listed next to the steps. A sample name is still populated above the list of steps with an ID number.
The steps have their samples identified next to them in the “Unknowns (machine)” tab.

[Waesche-DOO68.xlsx](https://github.com/NMGRL/pychron/files/5947565/Waesche-DOO68.xlsx)
[Waeshce-DOO68-groupbystep.xlsx](https://github.com/NMGRL/pychron/files/5947572/Waeshce-DOO68-groupbystep.xlsx)
![XLSoptions-unknowns](https://user-images.githubusercontent.com/58988891/107295963-b0f74600-6a2d-11eb-8394-09c1b25d6564.png)

Request: The table calculates Integrated Ages in the summary rows by Iso Recombination. There should be an option to calculate the integrate age by other means such as variance.

**Comment by jirhiker** [comment]
1. Main/Sorting is by age and really more for fusions i think.
2. fixed
3a. fixed
3b. if there is no plateau age then there is no cumulative %39Ar.  Its always 100% 
4. fixed
5. fixed
6. added asterisk to column header
7. not supported. cannot group steps from different samples currently. 
8. will implement soon
