### ISSUE TITLE
Flux not fitting for NM312-P and S

### ISSUE THREAD

**Issue by nelsiverson** [NMGRL/pychron#1938]
The SanidineDispersion project uses FC2-InclFree as the monitor. Not FC-2. At present, I can not save the flux to the database. 

It says the J is updated in the table but will not show up in the history. 

[Flux table.pdf](https://github.com/NMGRL/pychron/files/5960546/Flux.table.pdf)
[Flux history.pdf](https://github.com/NMGRL/pychron/files/5960547/Flux.history.pdf)

**Comment by jirhiker** [comment]
Flux fitting will never show up in an individual analysis' history as flux is applied to an irradiation position not an analysis. See #1749
