### ISSUE TITLE
Flux table copy to .cvs or save

### ISSUE THREAD

**Issue by nelsiverson** [NMGRL/pychron#1940]
Can you implement a way to save the Flux tables.  Matt H wants to compare the flux tables from PyChron to MassSpec. 
Making this table easy to copy or export to .cvs would be helpful. 

[Flux table.pdf](https://github.com/NMGRL/pychron/files/5960631/Flux.table.pdf)

**Comment by jirhiker** [comment]
all the flux values are easily retrievable from the irradiation level file. for example the flux values for NM-300A are in MetaData/NM-300/A.json

**Comment by jirhiker** [comment]
Added Share/CSV Flux Export
