### ISSUE TITLE
History in recall and Spectrum History not matching

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1948]
When viewing history of data reduction, this history via the recall window and history via the history node in the pipeline, the two histories do not match. Using example MW-031 L#66969-01. This data was 'worked up' in August 2019 and has not be worked until the IC update on Feb 8th, 2021. However, when viewing the history vis the History pipeline there appears to be ~25 additional history rows included refitting of isotope, blanks, IC factors which was done to this sample.
![Screen Shot 2021-03-16 at 10 18 13 AM](https://user-images.githubusercontent.com/6474471/111345718-26fd5700-8643-11eb-9156-594f395f5e59.png)

**Comment by jirhiker** [comment]
The two lists of changes represent different things.

The list of changes in the recall window is just the changes specific to that analysis.

The list of changes in the History Node is all the changes to repository(ies) that contain(s) the selected analyses

**Comment by mjz1983** [comment]
Making sure I understand. The history node is not specific to the sample, but to the repository. 

Let’s say I have two samples (A and B) in repository Z. I reduce A and B data at the same time thus have the sample history. But if I go back and refit the isotopes to B, the history node for A will also show a new fit to the isotopes. Is that correct?


Matt Zimmerer
Field Geologist II
New Mexico Bureau of Geology
New Mexico Tech
801 Leroy Pl
Socorro, NM 87801
***@***.***
575.835.5114

**Comment by jirhiker** [comment]
History node is not specific to the sample (currently). Its all the changes to the selected repository

Let’s say I have two samples (A and B) in repository Z. I reduce A and B data at the same time thus have the **SAME** history. But if I go back and refit the isotopes to B, the history node for **repository Z** will also show a new fit to the isotopes.

**Comment by jirhiker** [comment]
In the History Node I could see the benefit of only displaying the changes for the selected analyses. Ill look into that

**Comment by mjz1983** [comment]
Personally, I think only seeing the changes in the history to the sample, rather than the entire repository is more beneficial.

Z

Matt Zimmerer
Field Geologist II
New Mexico Bureau of Geology
New Mexico Tech
801 Leroy Pl
Socorro, NM 87801
***@***.***
575.835.5114
