### ISSUE TITLE
Add more sig figs options for summary info on data tables unknowns sheet

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1955]
Currently there is no option for controlling the number of sig figs for MSWD and 40/36 summary info on the unknowns sheets of the data tables.

**Comment by mjz1983** [comment]
Sig figs for MSWD working. Still no option for 40/36 intercept in summary rows for the unknowns sheets.

**Comment by jirhiker** [comment]
added 40/36 sigfigs
