### ISSUE TITLE
Incorrect order for step-heat data in data tables.

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1956]
Step heat data should ordered by step (A,B,C) or wattage on the data tables unknown sheet. Currently ordered by age, which is not standard listing procedures.

**Comment by jirhiker** [comment]
Sorting defined in XLSX Table Options

<img width="1212" alt="Screen Shot 2021-03-30 at 10 06 33 AM" src="https://user-images.githubusercontent.com/2035568/113020227-a0b33b80-913f-11eb-93d9-6c07d1f4385d.png">

**Comment by jirhiker** [comment]
ok. i concur. Should be fixed now. Setting "Individual" to --- should make it so individual analyses are not sorted by age.

**Comment by mjz1983** [comment]
OK. Will test soon.

Z
