### ISSUE TITLE
Add ability to set fixed plateau age to data tables

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1957]
Request to add fixed plateau ages to data tables. Perhaps this is done with the interpreted age and I need to be shown how to do it.

**Comment by jirhiker** [comment]
<img width="1877" alt="Screen Shot 2021-03-30 at 10 49 15 PM" src="https://user-images.githubusercontent.com/2035568/113091942-3c799180-91aa-11eb-800e-694794648f94.png">
