### ISSUE TITLE
Update age ± error info when hovering over a regression and selecting different fits

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1970]
If age ± error information is added to the info box when hovering over a regression fit in a recall window, then suggest adding the ability to updated the age when selecting a new fit in the recall regressions. A common procedure when working with data is to evaluate the impact of different fits to the data. Although this can be accomplished by running Iso Evo mutliple times with differing fits, it would be a potentially powerful tool to dynamically update the age. 

Running the Iso Evo pipeline would still be required to update and save the regression. However, the dynamic update to the age in the regression fit would be a temporary age calculation for evaluation data sensitivity to fits.

**Comment by jirhiker** [comment]
Does the age not update in the recall window when changing fits in the recall regressions? 
Does the age change if you right click on an isotope and change the fit from the floating regression window?

Ill add age info to the info box shortly #1969
