### ISSUE TITLE
remove small dot next to age

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1987]
When plotting an ideogram, a small dot is appearing to the left of the age information. Please remove. See attached screenshot
![Screen Shot 2021-05-25 at 10 48 02 AM](https://user-images.githubusercontent.com/6474471/119538578-7ac5a400-bd48-11eb-8870-e07966d73322.png)

**Comment by jirhiker** [comment]
![Screen Shot 2021-05-25 at 11 02 24 AM](https://user-images.githubusercontent.com/2035568/119538913-d132e280-bd48-11eb-9238-ce13332f53d2.png)

**Comment by mjz1983** [comment]
Copy that.
