### ISSUE TITLE
Iso Evo History repitition

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1989]
When fitting Iso Evo to analyses, the recall shows two lines/entries for the Iso Evo history (about ~15 sec apart) even though the pipeline procedure was only completed once. If this for real (there indeed are two fits)?

This doesn't appear to impact data but may be confusing to users investigating their history.

**Comment by jirhiker** [comment]
one is message is for the baseline fits and one is for the signal fits. Ill make that clearer
