### ISSUE TITLE
Diode laser turning off after moving

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#1994]
Currently when a diode experiment includes measure sample in two holes, treat as a single analysis, the laser stays on while moving to the second hole, then turns off, then turns on again. The timer for the duration of heating starts once the laser moves to the second hole. However, this is an overestimate for the duration of heating because it include the laser turning off and back on again.

Seems like the process should be 1) end heating of whole one, 2) turn off laser, 3) move to hole two, 4) turn on laser & start timer.

**Comment by jirhiker** [comment]
that is the sequence of events
https://github.com/NMGRLData/MetaData/blob/master/scripts/felix/felix_diode.py

1. move to position
2. fire laser for duration
3. disable laser
4. Goto 1
