### ISSUE TITLE
Inverse Isochron labels

### ISSUE THREAD

**Issue by cburrill** [NMGRL/pychron#1996]
The labels for points along the isochron currently include the aliquot and letter associated with the heating step. 
![MW-044-gms-67701-01-inviso](https://user-images.githubusercontent.com/58988891/122462565-feeb0000-cf71-11eb-8043-32d39c8f3c74.png)

When plotting just a single sample (or just one aliquot) it would be nice to just have the labels be the letters for the heating step.  Even when plotting multiple samples, if they are color coded then it would be nice to have the option to turn the aliquot part of the label on or off. 

One possibility could be adding this option in Inverse Isochron Options in the Main tab in the Labels section. 
Or maybe the aliquot number could just be removed entirely if others feel it isn't necessary to be part of the label.

**Comment by jirhiker** [comment]
You can configure the label format now

<img width="912" alt="Isochronlabels" src="https://user-images.githubusercontent.com/2035568/122468108-820f5480-cf78-11eb-80d3-dd0357b1c008.png">
