### ISSUE TITLE
Isochron Age Error 

### ISSUE THREAD

**Issue by cburrill** [NMGRL/pychron#2024]
The isochron age error calculated for the inverse isochron plot is different from the age error calculated for the 'spectrum/isochron' isochron plot. This appears to be the case for all my samples and not certain ones, but the difference between the errors is not the same from sample to sample. The isochron age error from the spectrum/isochron plot matches the isochron age error in the table created of the step heating data. Attached are two examples.
This error was seen on both windows (work desktop, windows 10 OS) and mac (computer in argon lab).

![isochronageerror2](https://user-images.githubusercontent.com/58988891/136319294-b4f3b4df-5ecd-4a78-b00c-f0c7cb779898.png)
![isochronageerror](https://user-images.githubusercontent.com/58988891/136319299-6da161e0-7110-4e4d-a381-6a7dce4fd76b.png)

**Comment by jirhiker** [comment]
This has to do with mixed Isochron Methods.  In the Isochron calculations you can set Isochron Method to York, NewYork, or Reed.  The table and spectrum/isochron use York by default. Working on adding the ability to set the method in Spectrum/Isochron; it was added table earlier today
