### ISSUE TITLE
Isochron regression options for Spectrum/Isochron plot

### ISSUE THREAD

**Issue by cburrill** [NMGRL/pychron#2039]
Noticed today (11/4/21) that the isochrons now use the New York regression for the Spectrum/Isochron plot. They had been using the York but I don't see an option to go back to using that regression. Can a box to select a regression be added to the options? Maybe under the Isochron tab.

Both regressions produce similar values for the error but in most cases the first decimal place is different so just don't want to have to redo all the tables I made.

**Comment by jirhiker** [comment]
That option is available in the "Calculations" tab for the Spectrum.  I will add to Spectrum/Isochron

<img width="912" alt="Screen Shot 2021-11-05 at 11 21 22 AM" src="https://user-images.githubusercontent.com/2035568/140552394-520a3573-bf64-4ddf-ad63-e676be5b97a6.png">
