### ISSUE TITLE
Missing data for 69249-01B

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#2062]
Step 69249-01B is missing from repository. Error window suggest pulling changes, but that doesn't appear to fix problem.

Any suggestions on how to retrieve that data
![Screen Shot 2021-12-21 at 9 29 43 AM](https://user-images.githubusercontent.com/6474471/146965404-ef5f490f-8f24-4ced-a532-4399f970f64e.png)
?

**Comment by jirhiker** [comment]
Fixed in latest update

**Comment by mjz1983** [comment]
Missing step now plotting. However, after updating the spectrum is not
plotting correctly and using fixed width or height does not work.
