### ISSUE TITLE
Spectrum not plotting correctly

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#2065]
When plotting a spectrum, the plot is "squished" vertically. Changing the vertical or horizontal fixed width doesn't appear to updating plot.
![Screen Shot 2022-01-03 at 1 25 24 PM](https://user-images.githubusercontent.com/6474471/147976910-d1592200-07b4-41d3-9704-594c2b47a55e.png)

**Comment by mjz1983** [comment]
Note, this became a project after the last updates on ~Dec. 23rd.

**Comment by jirhiker** [comment]
![Screen Shot 2022-01-03 at 1 37 24 PM](https://user-images.githubusercontent.com/2035568/147977831-5425bcf9-a3cd-4be9-b9a6-c9248d120419.png)
![Screen Shot 2022-01-03 at 1 37 33 PM](https://user-images.githubusercontent.com/2035568/147977832-2cb3ed4d-5b98-4503-8282-c3625e526496.png)
![69265-001](https://user-images.githubusercontent.com/2035568/147977970-e03dcc26-f069-40a0-815a-7ba52b10ff3f.png)

**Comment by mjz1983** [comment]
Suggests this might be a problem specific to ArgonLab2 (where I noticed the problem). We saw this on the newest lab computer and I think you though it was related to too many version on a computer.

???
Matt Zimmerer
Field Geologist II
New Mexico Bureau of Geology
New Mexico Tech
801 Leroy Pl
Socorro, NM 87801
***@***.***
575.835.5114

**Comment by jirhiker** [comment]
The issue appears when fixed_width and fixed_height are set to 0.  
a work around is to set fixed_width to a positive integer.

**Comment by jirhiker** [comment]
on closer inspection this is not a bug.

If fixed_width and fixed_height are not set then pychron respects the Height setting for each plot.  in the above example all the plots are set to a height of 100
