### ISSUE TITLE
Not able add new sample types in Probe Tracker

### ISSUE THREAD

**Issue by nelsiverson** [NMGRL/pychron#2073]
Environment:

Request Method: GET
Request URL: http://129.138.12.35:1338/materials/entry

Django Version: 3.2.7
Python Version: 3.9.6
Installed Applications:
['samples.apps.SamplesConfig',
 'projects.apps.ProjectsConfig',
 'materials.apps.MaterialsConfig',
 'principal_investigators.apps.PrincipalInvestigatorsConfig',
 'analyses.apps.AnalysisConfig',
 'events.apps.EventsConfig',
 'packages.apps.PackagesConfig',
 'irradiations.apps.IrradiationsConfig',
 'users',
 'crispy_forms',
 'django_tables2',
 'django_filters',
 'bootstrap3',
 'leaflet',
 'dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Probe tracker website will not let me add new samples types. 

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(

Exception Type: ValueError at /materials/entry
Exception Value: The view materials.views.entry didn't return an HttpResponse object. It returned None instead.

**Comment by jirhiker** [comment]
please submit this types of bugs to https://github.com/NMGRL/pychron_web/issues
