### ISSUE TITLE
Diode crosshairs not accurate

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#2119]
Both the crosshairs and aux crosshairs for the diode are not accurate (i.e., a 2mm crosshair is closer to 2.2 mm).

**Comment by jirhiker** [comment]
this is not a pychron issue necessarily, and should be logged at NMGRL/laboratory

calibration of the crosshairs is based on the Camera Coefficients. so any inaccuracy just means the Camera Coefficients need to be adjusted.  The Camera Coefficients convert the zoom value to pixels per mm
