### ISSUE TITLE
Unable to "Save As" for new diode patterns

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#2143]
When modifying an existing diode laser pattern, users currently cannot "save as".

**Comment by jirhiker** [comment]
What happens

**Comment by mjz1983** [comment]
Unable to write in a new file name.

Matt Zimmerer
Field Geologist II
New Mexico Bureau of Geology
New Mexico Tech
801 Leroy Pl
Socorro, NM 87801
***@***.***
575.835.5114

**Comment by jirhiker** [comment]
Ahh I see, the user literally cannot specify a name for the pattern. This was added in an attempt to reduce the clutter.

As a simple work around, Go to Pychron/setupfiles/patterns on the diode computer, duplicate the file manually
