### ISSUE TITLE
Auto linear vs. parabolic not working

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#2152]
When using the auto linear vs. parabolic for iso evo (for both Felix and Jan), the software is fitting linear fits to all isotopes.

Problem ID'd on ArgonLab 2. Appears to have originated after an update last week (last week of Feb.)

See attached example of a 40 beam that is clearly parabolic, but has been fit linear.

When using the auto linear vs. parabolic in the recall when, the preferred fit is parabolic.
![Screen Shot 2022-03-01 at 4 37 05 PM](https://user-images.githubusercontent.com/6474471/156267249-dcfe615d-6ace-46c2-ba40-c6eb264bb381.png)

**Comment by jirhiker** [comment]
I could not replicate this behavior on my computer
<img width="1519" alt="Screen Shot 2022-03-01 at 5 30 01 PM" src="https://user-images.githubusercontent.com/2035568/156272010-54f0e4a5-8719-415e-8427-ae3b3001c141.png">

The version on Argonlab2 must not be up to date, somehow. Can you replicate this behavior on different computers?

**Comment by mjz1983** [comment]
Bug is reproducible on ArgonLab3. All fits are linear, when clearly (your favorite word) are parabolic.
<img width="594" alt="Screen Shot 2022-03-02 at 11 04 40 AM" src="https://user-images.githubusercontent.com/6474471/156422324-2b1b0c96-2e43-4851-829f-314036ddd577.png">

**Comment by jirhiker** [comment]
This should now be resolved.  

note to myself. Once again this was a str comp case sensitivity issue.  maybe add a strcomp function
```def streq(a,b):
            return a.lower()==b.lower()
```

**Comment by mjz1983** [comment]
OK. Thanks. I too thought it was a str com case sensitivity issue.

I will update the lab comps.

**Comment by mjz1983** [comment]
Auto linear vs. parabolic is working, but the update has created a new bug. Double-clicking on Table iso evo rows produces an error which prevents the user from seeing the iso evo (t vs. intensity).
