### ISSUE TITLE
Sample trackers - sample's name bug

### ISSUE THREAD

**Issue by juliariccinmgrl** [NMGRL/pychron#2171]
Impossible to reach the information of a sample for changing them by clicking on its name (I would like to change a analyzed sample name for which there is an error). 

BUG:

<div id="summary" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(255, 255, 204); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="padding: 0px; margin: 0px; font-weight: normal;">ValueError at /samples/5009/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87);">Expected table or queryset, not SafeString</pre>

Request Method: | GET
-- | --
http://129.138.12.35:1337/labs/argon/sampletracker/samples/5009/
3.2.7
ValueError
Expected table or queryset, not SafeString
/usr/local/lib/python3.9/site-packages/django_tables2/templatetags/django_tables2.py, line 145, in render
/usr/local/bin/python
3.9.6
['/home/app/web',  '/usr/local/lib/python3.9/site-packages/git/ext/gitdb',  '/home/app/web',  '/usr/local/bin',  '/usr/local/lib/python39.zip',  '/usr/local/lib/python3.9',  '/usr/local/lib/python3.9/lib-dynload',  '/usr/local/lib/python3.9/site-packages',  '/usr/local/lib/python3.9/site-packages/gitdb/ext/smmap']
Mon, 23 May 2022 14:38:34 -0600

</div><div id="explanation" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(238, 238, 238); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="padding: 0px; margin: 0px;">You’re seeing this error because you have<span> </span><code style="padding: 0px; margin: 0px; font-size: 10.5625px; white-space: pre-wrap;">DEBUG = True</code><span> </span>in your Django settings file. Change that to<span> </span><code style="padding: 0px; margin: 0px; font-size: 10.5625px; white-space: pre-wrap;">False</code>, and Django will display a standard page generated by the handler for this status code.</p></div>ValueError at /samples/5009/
Expected table or queryset, not SafeString
Request Method:	GET
Request URL:	http://129.138.12.35:1337/labs/argon/sampletracker/samples/5009/
Django Version:	3.2.7
Exception Type:	ValueError
Exception Value:	
Expected table or queryset, not SafeString
Exception Location:	/usr/local/lib/python3.9/site-packages/django_tables2/templatetags/django_tables2.py, line 145, in render
Python Executable:	/usr/local/bin/python
Python Version:	3.9.6
Python Path:	
['/home/app/web',
 '/usr/local/lib/python3.9/site-packages/git/ext/gitdb',
 '/home/app/web',
 '/usr/local/bin',
 '/usr/local/lib/python39.zip',
 '/usr/local/lib/python3.9',
 '/usr/local/lib/python3.9/lib-dynload',
 '/usr/local/lib/python3.9/site-packages',
 '/usr/local/lib/python3.9/site-packages/gitdb/ext/smmap']
Server time:	Mon, 23 May 2022 14:38:34 -0600
Error during template rendering
In template /home/app/web/templates/base.html, error at line 52

Expected table or queryset, not SafeString
42	
43	    
44	    <div id='navbar' class="collapse navbar-collapse">
45	      <ul class="nav navbar-nav">
46	{#        <li {% if request.resolver_match.view_name == 'samples:index' %}class="active"{% endif %}><a#}
47	{#                href="/samples">Samples <span class="sr-only">(current)</span></a></li>#}
48	{#        <li {% if request.resolver_match.view_name == 'projects:index' %}class="active"{% endif %}><a#}
49	{#                href="/projects">Projects <span class="sr-only">(current)</span></a></li>#}
50	{#        <li {% if request.resolver_match.view_name == 'materials:index' %}class="active"{% endif %}><a#}
51	{#                href="/materials">Materials <span class="sr-only">(current)</span></a></li>#}
52	{#        <li {% if request.resolver_match.view_name == 'principal_investigators:index' %}class="active"{% endif %}><a#}
53	{#                href="/principal_investigators">Principal Investigators <span class="sr-only">(current)</span></a></li>#}
54	
55	          <li class="dropdown {% if request.resolver_match.view_name == 'principal_investigators:index' %}
56	              active {% endif %}">
57	              <a href="#" class="dropdown-toggle" data-toggle="dropdown"
58	                 role="button" aria-haspopup="true" aria-expanded="false">Principal Investigators</a>
59	              <ul class="dropdown-menu">
60	                  <li><a href={% url "principal_investigators:index" %}>View</a></li>
61	                  <li><a href={% url "principal_investigators:entry" %}>Entry</a></li>
62	              </ul>
Traceback [Switch to copy-and-paste view](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py, line 47, in inner
                response = get_response(request) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py, line 204, in _get_response
                response = response.render() …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/response.py, line 105, in render
            self.content = self.rendered_content …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/response.py, line 83, in rendered_content
        return template.render(context, self._request) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/backends/django.py, line 61, in render
            return self.template.render(context) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/base.py, line 170, in render
                    return self._render(context) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/base.py, line 162, in _render
        return self.nodelist.render(context) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/base.py, line 938, in render
                bit = node.render_annotated(context) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/base.py, line 905, in render_annotated
            return self.render(context) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py, line 150, in render
            return compiled_parent._render(context) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/base.py, line 162, in _render
        return self.nodelist.render(context) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/base.py, line 938, in render
                bit = node.render_annotated(context) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/base.py, line 905, in render_annotated
            return self.render(context) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py, line 62, in render
                result = block.nodelist.render(context) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/base.py, line 938, in render
                bit = node.render_annotated(context) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/base.py, line 905, in render_annotated
            return self.render(context) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py, line 312, in render
                return nodelist.render(context) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/base.py, line 938, in render
                bit = node.render_annotated(context) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django/template/base.py, line 905, in render_annotated
            return self.render(context) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
/usr/local/lib/python3.9/site-packages/django_tables2/templatetags/django_tables2.py, line 145, in render
            raise ValueError("Expected table or queryset, not {}".format(klass)) …
[▶ Local vars](https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/5009/#)
Request information
USER
jricci

GET
No GET data

POST
No POST data

FILES
No FILES data

COOKIES
Variable	Value
_pk_id.1.3a96	
'4a175ab6e01e4259.1634597827.'
style	
'null'
TRACKINGACCESSCODE	
'ff3d256f%2D1fa7%2D11ec%2Db84f%2D00155d020311'
_ga	
'GA1.2.338137670.1634772810'
CFID	
'8421751'
CFTOKEN	
'ea506e1cac1501dc-5684670B-FD2D-482D-1B9F42490B0B15A5'
PRIORITYMODALSHOWN	
'1'
COOKIESENABLED	
'TRUE'
LOGINFULLNAME	
'Julia%20Ricci'
SERVICECENTER	
'argon'
SERVICECENTERDESC	
'Geochronology%20Research%20Laboratory'
SALESPERSON	
'Julia%20Ricci'
CCMANAGER	
'1'
SALESPERSONPHONE	
'575%2D835%2D6333'
SALESPERSONEMAIL	
'julia%2Ericci%40nmt%2Eedu'
JSESSIONID	
'841AA6664C7ABABDACB5DCFD9A6F78F8.cfusion'
AUTHSET	
'TRUE'
_pk_ref.1.3a96	
'%5B%22%22%2C%22%22%2C1652297280%2C%22https%3A%2F%2Fwww.google.com%2F%22%5D'
csrftoken	
'caVONDo3wLsir66lP8zVUcIrlc6sPVyKgO4d8w0d4fXSEUqsdqOajmg0Aa2f8c7O'
sessionid	
'idnjusfyyo5fv3hdt172mditg8d3v2y7'
META
Variable	Value
CSRF_COOKIE	
'caVONDo3wLsir66lP8zVUcIrlc6sPVyKgO4d8w0d4fXSEUqsdqOajmg0Aa2f8c7O'
HTTP_ACCEPT	
'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
HTTP_ACCEPT_ENCODING	
'gzip, deflate, br'
HTTP_ACCEPT_LANGUAGE	
'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7'
HTTP_CONNECTION	
'close'
HTTP_COOKIE	
('_pk_id.1.3a96=4a175ab6e01e4259.1634597827.; style=null; '
 'TRACKINGACCESSCODE=ff3d256f%2D1fa7%2D11ec%2Db84f%2D00155d020311; '
 '_ga=GA1.2.338137670.1634772810; CFID=8421751; '
 'CFTOKEN=ea506e1cac1501dc-5684670B-FD2D-482D-1B9F42490B0B15A5; '
 'PRIORITYMODALSHOWN=1; COOKIESENABLED=TRUE; LOGINFULLNAME=Julia%20Ricci; '
 'SERVICECENTER=argon; '
 'SERVICECENTERDESC=Geochronology%20Research%20Laboratory; '
 'SALESPERSON=Julia%20Ricci; CCMANAGER=1; SALESPERSONPHONE=575%2D835%2D6333; '
 'SALESPERSONEMAIL=julia%2Ericci%40nmt%2Eedu; '
 'JSESSIONID=841AA6664C7ABABDACB5DCFD9A6F78F8.cfusion; AUTHSET=TRUE; '
 '_pk_ref.1.3a96=%5B%22%22%2C%22%22%2C1652297280%2C%22https%3A%2F%2Fwww.google.com%2F%22%5D; '
 'csrftoken=caVONDo3wLsir66lP8zVUcIrlc6sPVyKgO4d8w0d4fXSEUqsdqOajmg0Aa2f8c7O; '
 'sessionid=idnjusfyyo5fv3hdt172mditg8d3v2y7')
HTTP_HOST	
'129.138.12.35:1337'
HTTP_MAX_FORWARDS	
'10'
HTTP_REFERER	
'https://geoinfo.nmt.edu/labs/argon/sampletracker/samples/?name__icontains=Pow&materialid__name__icontains=&projectid__name__icontains=&projectid__principal_investigatorid__last_name__icontains=&state='
HTTP_SEC_CH_UA	
'" Not A;Brand";v="99", "Chromium";v="101", "Google Chrome";v="101"'
HTTP_SEC_CH_UA_MOBILE	
'?0'
HTTP_SEC_CH_UA_PLATFORM	
'"macOS"'
HTTP_SEC_FETCH_DEST	
'document'
HTTP_SEC_FETCH_MODE	
'navigate'
HTTP_SEC_FETCH_SITE	
'same-origin'
HTTP_SEC_FETCH_USER	
'?1'
HTTP_UPGRADE_INSECURE_REQUESTS	
'1'
HTTP_USER_AGENT	
('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, '
 'like Gecko) Chrome/101.0.4951.54 Safari/537.36')
HTTP_X_ARR_LOG_ID	
'2d02b717-67be-40fd-99c7-750861a402d2'
HTTP_X_ARR_SSL	
('2048|256|C=US, S=MI, L=Ann Arbor, O=Internet2, OU=InCommon, CN=InCommon RSA '
 'Server CA|C=US, S=New Mexico, O=New Mexico Institute of Mining and '
 'Technology, OU=NMBOGMR, CN=geoinfo.nmt.edu')
HTTP_X_FORWARDED_FOR	
'129.138.12.131:26913, 129.138.12.103'
HTTP_X_FORWARDED_PROTO	
'http'
HTTP_X_ORIGINAL_URL	
'/labs/argon/sampletracker/samples/5009/'
HTTP_X_REAL_IP	
'129.138.12.103'
PATH_INFO	
'/samples/5009/'
QUERY_STRING	
''
RAW_URI	
'/samples/5009/'
REMOTE_ADDR	
'172.18.0.2'
REMOTE_PORT	
'37316'
REQUEST_METHOD	
'GET'
SCRIPT_NAME	
'/labs/argon/sampletracker'
SERVER_NAME	
'0.0.0.0'
SERVER_PORT	
'8000'
SERVER_PROTOCOL	
'HTTP/1.0'
SERVER_SOFTWARE	
'gunicorn/20.1.0'
gunicorn.socket	
<socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.18.0.3', 8000), raddr=('172.18.0.2', 37316)>
wsgi.errors	
<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7ff3957b3c40>
wsgi.file_wrapper	
<class 'gunicorn.http.wsgi.FileWrapper'>
wsgi.input	
<gunicorn.http.body.Body object at 0x7ff3957b3dc0>
wsgi.input_terminated	
True
wsgi.multiprocess	
True
wsgi.multithread	
False
wsgi.run_once	
False
wsgi.url_scheme	
'http'
wsgi.version	
(1, 0)
Settings
Using settings module pychronweb.settings
Setting	Value
ABSOLUTE_URL_OVERRIDES	
{}
ADMINS	
[]
ALLOWED_HOSTS	
['geoinfo.nmt.edu',
 'pychronweb',
 '129.138.12.35',
 'localhost',
 '127.0.0.1',
 '[::1]']
ANALYSES_DEBUG	
False
APPEND_SLASH	
True
APP_TITLE	
'SampleTracker'
AUTHENTICATION_BACKENDS	
['django.contrib.auth.backends.ModelBackend']
AUTH_PASSWORD_VALIDATORS	
'********************'
AUTH_USER_MODEL	
'auth.User'
BASE_DIR	
PosixPath('/home/app/web')
CACHES	
{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS	
'default'
CACHE_MIDDLEWARE_KEY_PREFIX	
'********************'
CACHE_MIDDLEWARE_SECONDS	
600
CELERY_ACCEPT_CONTENT	
['application/json']
CELERY_BROKER_URL	
'redis://redis:6379'
CELERY_RESULT_BACKEND	
'redis://redis:6379'
CELERY_RESULT_SERIALIZER	
'json'
CELERY_TASK_SERIALIZER	
'json'
CRISPY_ALLOWED_TEMPLATE_PACKS	
'bootstrap3'
CRISPY_TEMPLATE_PACK	
'bootstrap3'
CSRF_COOKIE_AGE	
31449600
CSRF_COOKIE_DOMAIN	
None
CSRF_COOKIE_HTTPONLY	
False
CSRF_COOKIE_NAME	
'csrftoken'
CSRF_COOKIE_PATH	
'/'
CSRF_COOKIE_SAMESITE	
'Lax'
CSRF_COOKIE_SECURE	
False
CSRF_FAILURE_VIEW	
'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME	
'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS	
[]
CSRF_USE_SESSIONS	
False
DATABASES	
{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'mysql.connector.django',
             'HOST': '129.138.12.160',
             'NAME': 'pychrondvc',
             'OPTIONS': {},
             'PASSWORD': '********************',
             'PORT': '',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIGRATE': True,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': None,
             'USER': 'samplesubmit'}}
DATABASE_ROUTERS	
[]
DATA_UPLOAD_MAX_MEMORY_SIZE	
2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS	
1000
DATETIME_FORMAT	
'N j, Y, P'
DATETIME_INPUT_FORMATS	
['%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M']
DATE_FORMAT	
'N j, Y'
DATE_INPUT_FORMATS	
['%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y']
DEBUG	
True
DEBUG_PROPAGATE_EXCEPTIONS	
False
DECIMAL_SEPARATOR	
'.'
DEFAULT_AUTO_FIELD	
'django.db.models.AutoField'
DEFAULT_CHARSET	
'utf-8'
DEFAULT_EXCEPTION_REPORTER	
'django.views.debug.ExceptionReporter'
DEFAULT_EXCEPTION_REPORTER_FILTER	
'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE	
'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL	
'webmaster@localhost'
DEFAULT_HASHING_ALGORITHM	
'sha256'
DEFAULT_INDEX_TABLESPACE	
''
DEFAULT_TABLESPACE	
''
DISALLOWED_USER_AGENTS	
[]
DJANGO_TABLES2_TEMPLATE	
'django_tables2/bootstrap.html'
DOMAIN	
'geoinfo.nmt.edu'
EMAIL_BACKEND	
'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST	
'localhost'
EMAIL_HOST_PASSWORD	
'********************'
EMAIL_HOST_USER	
''
EMAIL_PORT	
25
EMAIL_SSL_CERTFILE	
None
EMAIL_SSL_KEYFILE	
'********************'
EMAIL_SUBJECT_PREFIX	
'[Django] '
EMAIL_TIMEOUT	
None
EMAIL_USE_LOCALTIME	
False
EMAIL_USE_SSL	
False
EMAIL_USE_TLS	
False
FILE_UPLOAD_DIRECTORY_PERMISSIONS	
None
FILE_UPLOAD_HANDLERS	
['django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE	
2621440
FILE_UPLOAD_PERMISSIONS	
420
FILE_UPLOAD_TEMP_DIR	
None
FIRST_DAY_OF_WEEK	
0
FIXTURE_DIRS	
[]
FORCE_SCRIPT_NAME	
'/labs/argon/sampletracker'
FORMAT_MODULE_PATH	
None
FORM_RENDERER	
'django.forms.renderers.DjangoTemplates'
IGNORABLE_404_URLS	
[]
INSTALLED_APPS	
['samples.apps.SamplesConfig',
 'projects.apps.ProjectsConfig',
 'materials.apps.MaterialsConfig',
 'principal_investigators.apps.PrincipalInvestigatorsConfig',
 'analyses.apps.AnalysisConfig',
 'events.apps.EventsConfig',
 'packages.apps.PackagesConfig',
 'irradiations.apps.IrradiationsConfig',
 'users',
 'stats',
 'crispy_forms',
 'django_tables2',
 'django_filters',
 'bootstrap3',
 'leaflet',
 'dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
INTERNAL_IPS	
[]
LANGUAGES	
[('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ar-dz', 'Algerian Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('dsb', 'Lower Sorbian'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-co', 'Colombian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gd', 'Scottish Gaelic'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hsb', 'Upper Sorbian'),
 ('hu', 'Hungarian'),
 ('hy', 'Armenian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('ig', 'Igbo'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kab', 'Kabyle'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('ky', 'Kyrgyz'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmål'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('tg', 'Tajik'),
 ('th', 'Thai'),
 ('tk', 'Turkmen'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('uz', 'Uzbek'),
 ('vi', 'Vietnamese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese')]
LANGUAGES_BIDI	
['he', 'ar', 'ar-dz', 'fa', 'ur']
LANGUAGE_CODE	
'en-us'
LANGUAGE_COOKIE_AGE	
None
LANGUAGE_COOKIE_DOMAIN	
None
LANGUAGE_COOKIE_HTTPONLY	
False
LANGUAGE_COOKIE_NAME	
'django_language'
LANGUAGE_COOKIE_PATH	
'/'
LANGUAGE_COOKIE_SAMESITE	
None
LANGUAGE_COOKIE_SECURE	
False
LEAFLET_CONFIG	
{'DEFAULT_CENTER': (35, -106.0),
 'DEFAULT_PRECISION': 6,
 'DEFAULT_ZOOM': 8,
 'MAX_ZOOM': 20,
 'MIN_ZOOM': 2,
 'TILES': []}
LOCALE_PATHS	
[]
LOGGING	
{}
LOGGING_CONFIG	
'logging.config.dictConfig'
LOGIN_REDIRECT_URL	
'signup'
LOGIN_URL	
'/labs/argon/sampletracker/accounts/login'
LOGOUT_REDIRECT_URL	
None
MANAGERS	
[]
MEDIA_ROOT	
''
MEDIA_URL	
'/labs/argon/sampletracker/'
MESSAGE_STORAGE	
'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE	
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']
MIGRATION_MODULES	
{}
MONTH_DAY_FORMAT	
'F j'
NUMBER_GROUPING	
0
PASSWORD_HASHERS	
'********************'
PASSWORD_RESET_TIMEOUT	
'********************'
PASSWORD_RESET_TIMEOUT_DAYS	
'********************'
PREFIX	
'/labs/argon/sampletracker'
PREPEND_WWW	
False
PYCHRON_DATA_ORGANIZATION	
'NMGRLData'
ROOT_URLCONF	
'pychronweb.urls'
SECRET_KEY	
'********************'
SECURE_BROWSER_XSS_FILTER	
False
SECURE_CONTENT_TYPE_NOSNIFF	
True
SECURE_HSTS_INCLUDE_SUBDOMAINS	
False
SECURE_HSTS_PRELOAD	
False
SECURE_HSTS_SECONDS	
0
SECURE_PROXY_SSL_HEADER	
None
SECURE_REDIRECT_EXEMPT	
[]
SECURE_REFERRER_POLICY	
'same-origin'
SECURE_SSL_HOST	
None
SECURE_SSL_REDIRECT	
False
SERVER_EMAIL	
'root@localhost'
SESSION_CACHE_ALIAS	
'default'
SESSION_COOKIE_AGE	
1209600
SESSION_COOKIE_DOMAIN	
None
SESSION_COOKIE_HTTPONLY	
True
SESSION_COOKIE_NAME	
'sessionid'
SESSION_COOKIE_PATH	
'/'
SESSION_COOKIE_SAMESITE	
'Lax'
SESSION_COOKIE_SECURE	
False
SESSION_ENGINE	
'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE	
False
SESSION_FILE_PATH	
None
SESSION_SAVE_EVERY_REQUEST	
False
SESSION_SERIALIZER	
'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE	
'pychronweb.settings'
SHORT_DATETIME_FORMAT	
'm/d/Y P'
SHORT_DATE_FORMAT	
'm/d/Y'
SIGNING_BACKEND	
'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS	
[]
STATICFILES_DIRS	
[]
STATICFILES_FINDERS	
['django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATICFILES_STORAGE	
'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_ROOT	
PosixPath('/home/app/web/staticfiles')
STATIC_URL	
'/labs/argon/sampletracker/static/'
TEMPLATES	
[{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': [PosixPath('/home/app/web/templates')],
  'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages']}}]
TEST_NON_SERIALIZED_APPS	
[]
TEST_RUNNER	
'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR	
','
TIME_FORMAT	
'P'
TIME_INPUT_FORMATS	
['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
TIME_ZONE	
'America/Denver'
USE_I18N	
True
USE_L10N	
True
USE_THOUSAND_SEPARATOR	
False
USE_TZ	
True
USE_X_FORWARDED_HOST	
False
USE_X_FORWARDED_PORT	
False
WSGI_APPLICATION	
'pychronweb.wsgi.application'
X_FRAME_OPTIONS	
'DENY'
YEAR_MONTH_FORMAT	
'F Y'
You’re seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.

**Comment by jirhiker** [comment]
@juliariccinmgrl The process for editing a sample that already has been analyzed is a little more complicated than one that has not. 

Currently there is no way to edit a sample that has been analyzed from SampleTracker. I will resolve the bug and the sample name issue next week
