### ISSUE TITLE
material not in recall window or on plot

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#2223]
Material is not being displayed in the recall window and thus not on the plot (autogenerate title). The material is entered into the package entry field. Using F20-91 from NM328-D as an example. Issue found on ArgonLab3. Screenshot included
<img width="706" alt="Screen Shot 2023-07-25 at 3 30 47 PM" src="https://github.com/NMGRL/pychron/assets/6474471/2f4db504-30b6-454c-90aa-8e85b23ac583">

**Comment by jirhiker** [comment]
Likely the material info was added after the sample was analyzed.  You need to SyncRepo/ DB Sample Info if you want to update the analysis files with the current database information
