### ISSUE TITLE
spectrum log scale

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#499]
When I plot an age spectrum, with K/Ca set to log, the scale does not appear to be a correct log scale
e.g. run 63392-01

**Comment by jirhiker** [comment]
@wcmcintosh I believe this has been a long standing issue that is not unique to K/Ca but is related to the range.  If the range is less than X (maybe 1 or 2 log units) the graphical package doesn't render the ticks correctly. Also negative values maybe an issue. 

Is it an issue with the y axis ticks or actually not laying out the data points correctly.

**Comment by jirhiker** [comment]
Neither of the above comments were applicable to the current issue. 
Spectrum._add_plot simply had the y scale hardcoded as "linear"

**Comment by wcmcintosh** [comment]
I think that the data is being plotted on a log scale correctly, but it is a little hard to tell because only one tick mark is being shown. Manual tic interval selection is not appropriate for log scale. Auto selection should show a minimum of two tic marks.

**Comment by jirhiker** [comment]
Need to make grid lines match ticks when log scale
