### ISSUE TITLE
spectrum plot alignment

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#500]
When I plot an age spectrum, the horizontal alignment of individual steps in all plots is slightly off, by a small number of pixels, both on screen and on the pdf.

**Comment by wcmcintosh** [comment]
This slight offset changes sense (right or left)  depending on whether uncertainty boxes as filled or not. Perhaps line width is a factor here.

**Comment by wcmcintosh** [comment]
In a related issue, the ± sigma label does not appear to change when the error envelope is changed.  The actual error envelope is fine, just not the label.

**Comment by jirhiker** [comment]
@wcmcintosh  include screenshots.

"Attach images by dragging & dropping,  selecting them, or pasting from the clipboard."
