### ISSUE TITLE
40/36 auxiliary spectrum plot

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#503]
Could an option be added to plot 40/36 ratio as an auxiliary plot of the age spectrum to help address the Matt Z negative age problem.

**Comment by wcmcintosh** [comment]
Ideally, the 40/36 ratio should be corrected for interfering reactions, but not atmosphere.

**Comment by jirhiker** [comment]
add 3 40/36 aux plots

- [ ] 40/36  raw intensities
- [ ] 40/36_IC ic corrected
- [ ] 40/36_IF ic and interference corrected
