### ISSUE TITLE
2 Hour Diode Bakeout not stop heating

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#507]
When baking the diode laser chamber using the Diode-2 hour.cfg configuration file, which uses the script backout150-2.py, the diode chamber does not stop heating after two hours. The timer counts down from 2 hrs to 0 hrs and continues into negative time.

User must stop heating experiment by clicking stop. 

Attached screen shot shows negative time and associated logger.
![screen shot 2015-01-14 at 1 42 33 pm](https://cloud.githubusercontent.com/assets/6474471/5747363/9472de26-9bf4-11e4-9b7b-2b21f12a71d7.png)

**Comment by wcmcintosh** [comment]
Problem is that the bakeout gosubs do not have access to the controller object.
