### ISSUE TITLE
Age error w/o J display in ratio tab

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#513]
Age w/o J display in ratio tab displays NaN for percent error

**Comment by wcmcintosh** [comment]
This is on dock version on Jan

**Comment by jirhiker** [comment]
What is the version. dock version on Jan is not enough. 
should be something like pyview_devrc4. or pyview_v2.0.4rc1

What is an example analysis that shows this behaviour

**Comment by wcmcintosh** [comment]
version is  pyexperiment_v2.0.4rc1
F error w/o J also has NaN as % error
