### ISSUE TITLE
Incorrect valve lock states

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#533]
Jan has incorrect valve lock state for valve Z causing valve Z not to open when running Air. Air analyses are at blank level.  Fixed by restarting PyExperiment.  Similar behavior observed previously on some Obama valves, i.e., Pychron has valve lock state that doesn't match PyValve.

**Comment by jirhiker** [comment]
a log file would help. 

no smoking gun in the code so extensive testing would be necessary to track this down. 

Note: valve lock states are only updated every 10s
