### ISSUE TITLE
List box behavior-browser+

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#534]
Is it possible to for a list box with slider to be positioned on a already selected item, in the cases where something is preselected?  E.g., in the project list box, if a project is selected but is not within one screen of the beginning of the list, then the list box gives the impression that nothing is selected. 
The same behavior holds for some lists boxes in the data entry window,

**Comment by jirhiker** [comment]
Auto scroll to the selected item

**Comment by jirhiker** [comment]
use an explicit scroll to row when the browser is activated
