### ISSUE TITLE
spectrum axis titles

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#535]
Spectrum axis title font size not changable

helvetica font not working for plus/minus or sigma.  Can we use a more symbol-friendly font?

**Comment by jirhiker** [comment]
Currently Helvetica is the only font the can be used both as a screen font and a pdf font. 

It will be a massive effort to make this better and its not a valuable use of my time at this point. 

It would be great to have a better handle on fonts

**Comment by jirhiker** [comment]
Cannot reproduce symptoms. 

One thing to note is that the "global" formatting option (i.e. screen, presentation,...etc) trumps the Figure Options font settings when the figure is first made.
