### ISSUE TITLE
Pychron vs mass spec values

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#536]
Does Py-view still have the ability to compare values with mass spec?

**Comment by nmgrluser** [comment]
Chris and I are looking for the source of a 20 ka difference in age of a 185 ma analysis

**Comment by jirhiker** [comment]
Yes

0. goto preferences and make sure a valid MassSpec database connection is defined
1. recall an analysis, and hit "Diff" on the toolbar.
