### ISSUE TITLE
spectrum boxes

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#538]
Spectrum boxes could be on pixel wiser on both ends.  I though that this had already been modified.

Also, do I remember option to urn on and off the heating step centerline and the grid markers?

**Comment by nmgrluser** [comment]
I found the gridline option in the graph editor, but I can't make it work.

**Comment by nmgrluser** [comment]
I can get them to turn off, but they reappear on replot.  The choices do not seem to persist either.

**Comment by nmgrluser** [comment]
If I select one graph and shut off the grid, all graphs lose their grid briefly, but all come back on replot.

**Comment by jirhiker** [comment]
Ive said this many times, right or wrong, changes made in the graph editor are not persisted!
