### ISSUE TITLE
blank default

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#544]
should blank duration and cleanup default to 30/30, in the absence of unknowns?

**Comment by wcmcintosh** [comment]
I vote yes.

Bill
William McIntosh
Geochronologist/Volcanologist
NM Bureau of Geology
Associate Professor
Earth and Environmental Science Dept
NM Tech
801 Leroy Place
Socorro, NM 87801
575-835-5271
mcintosh@nmt.edu
