### ISSUE TITLE
ideogram - deleted lines 

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#575]
if data is manually deleted from run list, it reappears when pipeline is rerun

**Comment by jirhiker** [comment]
The analysis table is tied to the selected node so deleting analyses from the table only applies to the current selected node. So its not that its reappearing its that you were deleting analyses from the IdeogramNode not the UnknownsNode. 

This behavior could be desirable in some cases but as a default for now deletions from non UnknownsNodes will be applied to the UnknownsNodes
