### ISSUE TITLE
ideogram padding

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#577]
As per attached figure, x min and max coincide with max and min of analysis error bars, which truncates a significant amount of the probability curves. Can appropriate padding be added to address this?

[BW-2014-6.pdf](https://github.com/NMGRL/pychron/files/1012/BW-2014-6.pdf)

**Comment by jirhiker** [comment]
A configurable x pad value will be added. 

you can also you "asymptotic limits" to avoid this problem.

**Comment by wcmcintosh** [comment]
I tried asymptotic limits, but wasn't 't sure how it worked

William C McIntosh

**Comment by jirhiker** [comment]
Fix asymptotic limits. 
specify a height in %

calculate  x0 and x1 such that f(x0)<h and f(x1)<h
