### ISSUE TITLE
Ideogram proportions

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#578]
Currently, the screen appearance and pdf dimensions vary with the size and shape of the screen display window.  Making these dimensions independent of window dimensions would make for better controlled figures, especially with selectable formats of publication (page width, 1/2 column, 1/3 column, 2/3 column).

**Comment by jirhiker** [comment]
add a save pdf configuration dialog. 
options
* fit to page
* fixed width, height
* padding
* width as page percent
* page width, 1/2, 1/3, 2/3,
