### ISSUE TITLE
fonts, ideogram

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#600]
I downloaded from the web and added Helvetica.ttf and Arial.ttf to both my library font folders. Whan helvetica is selected, nothing is change (italics, A arete, etc.) .  When I change to Arial it fixes the horizontal label, but nothing else.

**Comment by jirhiker** [comment]
you have to clear the font cache. Delete file ~/.enthought/kiva/fonList.cache

What is horizontal label? You have individual control over the font for different elements. so changing the mean indicator label doesn't affect the axis labels or the error info label. 

This does not seem a desirable behavior. A better setup would be to have a fonts tab the allows the user to set the font face name globally for all elements and the font size is individually controllable. (make the font face names individually editable but also add a global option)
