### ISSUE TITLE
Inconsistent results using Touptek Camera

### ISSUE THREAD

**Issue by lefsky** [NMGRL/pychron#604]
I have been obtaining inconsistent but mostly negative results using pychron to interface to a touptek camera. For instance, I can retrieve some basic information (i.e. serial number) but not others (e.g. size of image) and I can't get it to snap a still.  Is this part of the software still in a development phase?

**Comment by jirhiker** [comment]
I haven't worked on ToupCamCamera class for a few months but when I last used it most features were working. 

If I remember correctly, tho, ToupCamCamera.save was not working. In order to save a still use ToupCamCamera.get_pil_data()
e.g
```
cam = ToupCamCamera()
cam.open()
im = cam.get_pil_data()
with open('snapshot.jpg', 'w') as wfile:
    im.save(wfile, 'JPEG')
```

**Comment by lefsky** [comment]
Thanks for the reply. Can you tell me what hardware you were running this code on? I have had terrible luck with the Toupcam I have depending on which USB hardware I was using. Looks like it was a mac based on the use of dylib.

**Comment by jirhiker** [comment]
Im using MacBook Pro (mid 2014) OSX 10.10.4 with an OMAX A35100U3 10MP USB 3.0 camera

**Comment by lefsky** [comment]
And that's a touptek camera under another brand name?

On Sunday, September 6, 2015, Jake Ross <notifications@github.com> wrote:

> Im using MacBook Pro (mid 2014) OSX 10.10.4 with an OMAX A35100U3 10MP USB
> 3.0 camera
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NMGRL/pychron/issues/604#issuecomment-138101362>.
>


-- 
Michael Lefsky
Center for Ecological Applications of Lidar
College of Natural Resources
Colorado State University
http://www.researcherid.com/rid/A-7224-2009

If I were creating the world I wouldn't mess about with butterflies and
daffodils. I would have started with lasers, eight o'clock, Day One! - Time
Bandits

**Comment by jirhiker** [comment]
Yea. Its a Touptek U3CMOS series.

**Comment by lefsky** [comment]
Jake,

Thanks again.

I am going to be looking for a programmer that has experience in python to
work on the software needed collect and process images from an aerial film
scanner of my own design. Briefly, the scanner consists of an array of
cameras that are used to scan 9 x 9 inch aerial photos at a resolution of
6.5 um. The camera array needs to be calibrated for focus, radiometry and
geometric position and the software needs to integrate the motion of the
camera array in 2 dimensions as well as controlling film advance and
holding mechanisms. It then needs to position and mosaic the individual
images to create a single image.

I have no idea if you pursue programming outside of your Ar-Ar
geochronology research, but you seem to be perfect for this type of job.

M

On Mon, Sep 7, 2015 at 4:56 PM, Jake Ross <notifications@github.com> wrote:

> Yea. Its a Touptek U3CMOS series.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NMGRL/pychron/issues/604#issuecomment-138388643>.
>



-- 
Michael Lefsky
Center for Ecological Applications of Lidar
College of Natural Resources
Colorado State University
http://www.researcherid.com/rid/A-7224-2009

If I were creating the world I wouldn't mess about with butterflies and
daffodils. I would have started with lasers, eight o'clock, Day One! - Time
Bandits

**Comment by lefsky** [comment]
Jake,

I'd rather be talking high level design of the application I envisage, but
right now I could use some practical advice.

I have been an awful time getting the toupcam to work on any platform other
than windows (and even then it is inconsistent). I am trying it on a
macbook with osx 10.9.5 as this is the closest I have to your hardware.
When I run ToupLite, it starts and allows me to select the camera but the
stalls and gives me an error window "Cannot preview, please re-plug the
device and try again". Needless to say, re-plugging it doesn't work.

Have you had similar problems? I've contacted Touptek, but they have
nothing to suggest.

M


On Mon, Sep 7, 2015 at 5:16 PM, lefsky@gmail.com <lefsky@gmail.com> wrote:

> Jake,
>
> Thanks again.
>
> I am going to be looking for a programmer that has experience in python to
> work on the software needed collect and process images from an aerial film
> scanner of my own design. Briefly, the scanner consists of an array of
> cameras that are used to scan 9 x 9 inch aerial photos at a resolution of
> 6.5 um. The camera array needs to be calibrated for focus, radiometry and
> geometric position and the software needs to integrate the motion of the
> camera array in 2 dimensions as well as controlling film advance and
> holding mechanisms. It then needs to position and mosaic the individual
> images to create a single image.
>
> I have no idea if you pursue programming outside of your Ar-Ar
> geochronology research, but you seem to be perfect for this type of job.
>
> M
>
> On Mon, Sep 7, 2015 at 4:56 PM, Jake Ross <notifications@github.com>
> wrote:
>
>> Yea. Its a Touptek U3CMOS series.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/NMGRL/pychron/issues/604#issuecomment-138388643>.
>>
>
>
>
> --
> Michael Lefsky
> Center for Ecological Applications of Lidar
> College of Natural Resources
> Colorado State University
> http://www.researcherid.com/rid/A-7224-2009
>
> If I were creating the world I wouldn't mess about with butterflies and
> daffodils. I would have started with lasers, eight o'clock, Day One! - Time
> Bandits
>



-- 
Michael Lefsky
Center for Ecological Applications of Lidar
College of Natural Resources
Colorado State University
http://www.researcherid.com/rid/A-7224-2009

If I were creating the world I wouldn't mess about with butterflies and
daffodils. I would have started with lasers, eight o'clock, Day One! - Time
Bandits

**Comment by jirhiker** [comment]
I've used ToupViewX and ToupLite and haven't seen the error you mentioned. Sounds a bit more like a camera hardware problem than software if you're having trouble on various platforms.  Are you going directly from the computer to the camera or is there a usb hub in between?

**Comment by lefsky** [comment]
Directly- this is a new camera model so the hardware problem is possible.

On Fri, Sep 11, 2015 at 8:44 AM, Jake Ross <notifications@github.com> wrote:

> I've used ToupViewX and ToupLite and haven't seen the error you mentioned.
> Sounds a bit more like a camera hardware problem than software if you're
> having trouble on various platforms. Are you going directly from the
> computer to the camera or is there a usb hub in between?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NMGRL/pychron/issues/604#issuecomment-139564540>.
>



-- 
Michael Lefsky
Center for Ecological Applications of Lidar
College of Natural Resources
Colorado State University
http://www.researcherid.com/rid/A-7224-2009

If I were creating the world I wouldn't mess about with butterflies and
daffodils. I would have started with lasers, eight o'clock, Day One! - Time
Bandits

**Comment by jirhiker** [comment]
A separate toupcam project has been created at github.com/NMGRL/toupcam. 

This project should be used instead of pychron if you want to use ToupTek cameras with python
