### ISSUE TITLE
IC fit

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#617]
IC fit seems to be working great, but I can't seem to repeat yesterday's results.  How can I access a previous fit on airs to see which references were used and which excluded?

**Comment by jirhiker** [comment]
Current there is no UI for accessing that information directly but you can examine the icfactor file to see which references were used. e.g
```
experiment_identifier: Foo
analysis: 12345-01

file located at
Pychron/data/.dvc/experiments/Foo/123/icfactors/45-01.icfa.json

```
