### ISSUE TITLE
pipeline blank fit mostly OK

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#621]
pipeline blank fit applying and saving blank values correctly

just need more fitting options - preceding, following, etc.

**Comment by wcmcintosh** [comment]
above issue should have been combined with #618

**Comment by wcmcintosh** [comment]
I would like to see the mathematics on the current default linear fit for blanks.  Error envelope empirically looks good.  Nearly but not quite constant around fit line

**Comment by jirhiker** [comment]
see **Draper and Smith chapter 2.4 page 56**
