### ISSUE TITLE
browser previous selection problem?

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#623]
should the upper right pull-down in the browser be a list of previous selections?  currently it appears to be a list of single analyses

**Comment by jirhiker** [comment]
No. That is for filtering the table.

It will be changed to a simple text field and will use fuzzy filtering.  The drop down to the left is to select which column to filter on. 

Fuzzy filtering is especially useful when trying to locate a specific Air, Blank, etc.
For example if you are looking for a-01-j-1590, simply typing 159 will limit the selection to only analyses with 159 in the RunID. (i.e you don't have to type a-01-j-159...)
