### ISSUE TITLE
Ar41 in Isotope evolution plot does not scale to dataset

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#639]
Pychron automatically scales the isotope evolution plots to match the data set collect for all isotopes except Ar41. Suggest changing to automate this or allowing user to manually change the verticle axis (i.e., intensity). See image comparing Ar40 and Ar41
![screen shot 2015-09-22 at 9 35 48 am](https://cloud.githubusercontent.com/assets/6474471/10023115/8fa4885c-610d-11e5-8e68-09a3a19e6afd.png)

**Comment by jirhiker** [comment]
see #637
