### ISSUE TITLE
pipeline ideogram-significant digits

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#648]
How are significant digits in the mean calculation set? In the calculations tab, could the user choose automatic or manual setting of the significant digits?  Al's automatic setting of significant digits in figures was nice up to a point, but there were many many circumstances where I has to modify them after the fact in illustrator.

**Comment by jirhiker** [comment]
sig figs for mean are set in IdeogramOptions/Display. 

there are no plans to implement an automatic sig fig determination.  However if sig figs is set to 1 and the error is 0.01, 0.01 will be displayed instead of 0.0

**Comment by wcmcintosh** [comment]
I must be missing something here, but I don't see IdeogramOptions/Display when I click the ideogram node.

**Comment by wcmcintosh** [comment]
sorry, just found it

**Comment by wcmcintosh** [comment]
works perfectly
