### ISSUE TITLE
spectrometer scan function?

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#673]
Does the spectrometer window haw the ability to scan?  We see upper and lower limits (defaulting to 0 and 200) but don't see a scan function?Are we just missing it?  If there is no scan function, could one be added?

**Comment by wcmcintosh** [comment]
hAVE

**Comment by jirhiker** [comment]
The spectrometer window does (or has had) the ability to scan (i.e sweep) the magnet. 

the Jan version (v2.1.0) may have it. Goto the Menubar/View. At the bottom of the list there may be "Scanner"
