### ISSUE TITLE
wrong counts

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#680]
While running a-01-3428 on Jan the data collection appeared to me missing several points and the total count time was way too long. When plotted in mass spec, the data appeared to be collected, but far too much more than specified in the measurement script.

See screen shot on Jan Desktop

Screen Shot 2015-10-18 at 11.30.32 AM

```
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/enable/qt4/base_window.py", line 244, in sizeHint
    return self.handler.sizeHint(qt_size_hint)
  File "//anaconda/lib/python2.7/site-packages/enable/qt4/base_window.py", line 141, in sizeHint
    q_size = self._enable_window.control.size()
AttributeError: 'NoneType' object has no attribute 'size'

```

**Comment by jirhiker** [comment]
I suspect this is an App Nap issue. I will disable App Nap asap
