### ISSUE TITLE
pipeline iso ev pre save pause

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#686]
In iso ev, even if save is checked, pipeline pauses at save iso ev node until resume button is pushed, the save occurs

Is this the desired behavior?

**Comment by jirhiker** [comment]
Not clear on what you mean. 
1. Having the save checkboxes checked simply means that you intend to save this evo and not just plot it or determine its value. 
2. Pauses only happen at the Review nodes.

The pipeline I use for iso evo fitting is
1. Unknowns
2. Fit IsoEvo
3. Review
4. Save Iso Evo

the pipeline runs up to the Review node giving the user a chance to review the fits. If they are acceptable then the pipeline is resumed, the fits are saved and the pipeline is finished.
