### ISSUE TITLE
possible iso ev enhancement for future

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#687]
another iso ev thought for the future: In the iso ev results tab, would it be advantageous to automatically flag fits that fail to meet some set criteria?  Some criteria along the lines of precent error in intercept as a function of signal size might be appropriate. This would alert the user if some fits looked bad and might help identify popcorn and other detector misbehaviors

**Comment by jirhiker** [comment]
This falls into the same category as using a Classifier (e.g Weak AI) to identify good and bad analyses. if the dimensionality of the problem space is only percent error than a classifier is probably overkill and simple criteria thresholding would be adequate. 

The criteria thresholding is simple enough to add but it's up to the user to define the magnitude of the threshold e.g. >X% == bad <=X% == good and the user defines X.

also isn't percent error always a function of signal size. percent means error/signal
