### ISSUE TITLE
Spectrum questions

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#697]
1) what does the bind colors checkbox do?

2) Can you remind where the gridline settings is?  I must be looking right at it.

**Comment by wcmcintosh** [comment]
In the spectrum node settings, "Calculations" might be better termed "Plateau"

I dee that line type is an editable field.  Should it be a pull-down?

**Comment by jirhiker** [comment]
1. Bind colors- if checked if change error envelope color the plateau color will change to match and vis versa.

2. gridline settings not currently available.
3. Calculations change to Plateau
4. That field is no longer relevant. Set the line style per group in the Group tab.
