### ISSUE TITLE
Diode laser position not moving

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#699]
Received this error message (see screen shot). After firing laser at first of three holes, message appeared on screen. Laser kept rastering in the same hole, although it was supposed to move to the second (and then third) holes for this step. This problem occurred twice. Restarted PyDiode after first crash. Stopped experiment after second crash.

![screen shot 2015-11-03 at 7 22 26 pm](https://cloud.githubusercontent.com/assets/6474471/10927841/69742cae-8260-11e5-8055-e615d79703fe.png)

**Comment by jirhiker** [comment]
could not replicate error. launched pydiode and pyexperiment. ran a test analysis at low power and patterning worked as expected; executed square pattern at hole 4 then 5 then 6. 

When you ( @mjz1983 ) say crash do you mean that pydiode quit unexpectedly or simply that you received the PositionError message?

**Comment by mjz1983** [comment]
Replicated the error during first analyses this morning. I received the same error (same numbers, same hole requested). PyDiode continued to move to the correct position. When I clicked OK, PyDiode quit unexpectedly.
