### ISSUE TITLE
automatic versus chaotic naming

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#707]
could many names that are currently user assigned instead be provided by pychron, yet retain user access ability

some examples - step heat schedules, experiment names

e.g. HeatingSchedule1, HeatingSchedule2, or Experiment1, Experiment2, etc.

I know you are not fond of messy list like the current versions of these

**Comment by jirhiker** [comment]
added  name generation.
the name format is 
<nsteps>Steps<value_0>-<value_n-1>_<hash>
e.g
6Steps1.0-5.0_adefab4

**Comment by jirhiker** [comment]
added name generation to experiment queues

```
Load <load_name>.txt
```
e.g.

```
Load 1684.txt
```

**Comment by jirhiker** [comment]
added Save As Current Experiment... action to help enforce that model
