### ISSUE TITLE
automate approximate J

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#717]
When approximate J's are entered they are frequently far from correct.  Pychron could do better by making approximate J a function of irradiation duration, especially if we refined the J per hour value by plotting J vs irradiation duration and regressing the value, which would also provide an error value, which would encompass average J range over x,y, and z.  

A pychron assigned value would do away with the large inaccuracy in approximate J values that we currently get by just winging it, e.g. using 20 minute values for 30 minute irradiations.

A small problem, but readily addressable.

**Comment by jirhiker** [comment]
A basic version of assigning an approximate J is already implemented. 

a configurable J multiplier value is saved in preferences and multiplied by the irradiation duration

an "estimate j" button is provided to set the J for the current level. 

more sophisticated procedures can be added on demand
