### ISSUE TITLE
Wrong Min decay constant value

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#808]
The total decay constant for Min et al. (2000) is 5.463 x 10^-10/yr. In PyView preferences it is listed as 5.464x10^-10/yr. The total value in preference should also include /yr or yr^-1.
![screen shot 2016-05-12 at 3 02 14 pm](https://cloud.githubusercontent.com/assets/6474471/15230444/e18f8d0e-1852-11e6-8988-1057e5196af2.png)

**Comment by jirhiker** [comment]
well then total lambdaK is not equal to the of epsilon and beta.

from Min et al 2000 table 3.
beta = 0.580 +/-0.014 x10-10
epsilon = 4.884 +/- 0.099 x10-10
total = 5.463 +/- 0.107 x10-10
