### ISSUE TITLE
co2 calibration

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#834]
as previously discussed, could we try a modified calibration routine that starts with two user points for rotation, then performs auto calibration from there using the determined rotation value

I realize this still requires user selection, but it might be a step in the right direction until we can better control chamber/movement/camera orientation

**Comment by jirhiker** [comment]
auto rotation calibration can be disabled by deleting the calibration holes in the tray file. 
lets try this approach before doing any programming
