### ISSUE TITLE
blank fitting history problem?

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#837]
in history (see screen shot) blank refit lists Ar41 twice, but no Ar36 in list
<img width="1440" alt="screen shot 2016-06-01 at 5 16 26 pm" src="https://cloud.githubusercontent.com/assets/6126423/15728911/e86e0a18-281c-11e6-9922-f0c5a31450d4.png">

**Comment by jirhiker** [comment]
I suspect user error. Check your fits to make sure you don't have Ar41 twice
