### ISSUE TITLE
baseline average problem

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#845]
using BU-FC-J-5681, H1 baseline as an example, it appears that whether or not the filter is turned on, the average value that is shown in the table and is saved is the unfiltered version

BU-FC-J-5681, H1 baseline, filtered, 
      regression value = -0.0.510, value shown in table (see below) and saved = -0.0506

BU-FC-J-5681, H1 baseline, unfiltered, 
      regression value = -0.0.506, value shown in table (see below) and saved = -0.0506

[t.pdf](https://github.com/NMGRL/pychron/files/305981/t.pdf)

**Comment by jirhiker** [comment]
t.pdf is not attached

attach png's instead of pdf's when including screenshots
