### ISSUE TITLE
error reporting button

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#889]
could we add a default password so error reporting is always possible, and reportable errors will not cause Python to quit

**Comment by jirhiker** [comment]
No

**Comment by wcmcintosh** [comment]
Doesn't it kind of defeat the purpose if error reporting causes python to quit?

**Comment by jirhiker** [comment]
maybe. But there will **NEVER** be a default password. This as a huge vulnerability and would make it exceedingly easy for labs github account to be hacked.
