### ISSUE TITLE
autocalibration enhancement suggestions

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#891]
Here are a few suggestions - none critical

- [x] 1. give user a button to trigger auto center
- [ ] 2. autocenter on center hole if not already centered on
- [x] 3. return to center hole after calibration
- [x] 4. add full auto option - the only difference being auto location of center hole, keying on either homed position, or working from edge of pattern
- [ ] 5. although auto calibration is working, could a safety margin be added by working from the middle row outward, e.g. previous circle pattern, thereby avoiding a large offset that is more likely to eventually miss a hole, especially in an HF reduced tray

- [ ] 6. could a little more be done with the diameter of the central hole? e.g. add crosshair kind choice  that automatically fits cross hair diameter to tray type for calibration?  And/or a context sensitive  automatic setting that fit to tray hole size for calibration, and laser spot size otherwise?

**Comment by jirhiker** [comment]
4. need to add a new configuration file that defines the absolute x,y position of the center hole. name something like <tray_name>.center.txt. Will require a button in Calibration that allows user to set this value. 
5. Come up with an algorithm to calculate traversal holes. 
6. Not sure on the application/utility of this request
