### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by jirhiker** [NMGRL/pychron#904]
create a mechanism to save and load recipe files for figures and tables
use a yaml file
- list of analyses
- head commit for each analysis
- options

when recipe is opened load into pipeline.

add RecipeNode for saving recipes of the current pipeline.

**Comment by wcmcintosh** [comment]
This would be really great to implement if you can fit it in.
I also see that this bears in my vision of data processing automation.
The pipeline would automatically build appropriate recipes for each set of analyses.  The user would modify the recipes by referring isotopes, IC, blank, tagging samples, adjusting scales, etc., with the modified recipes persisting.
My vision.
