### ISSUE TITLE
Possible blank fit problem?

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#912]
Jake, I am fitting blanks for NM281C monitors, and wonder about a couple of things.

1) previously, could one hover over a blank in the fit screen and see the number analysis number pop up?
2) in the blank options box, how can one delete or null out an isotope line?
3)something looks funny in the reference display for some isotopes. 40 and 36 look ok
but 41 and 37 have identical values, and 38 and 39 have identical values

**Comment by wcmcintosh** [comment]
Actually, not the exactly same values, but the reference isotope errors don't seem right - they don't jive with the saved values

**Comment by jirhiker** [comment]
1. functionality moved to `Inspector` pane
2. click the `Enabled` checkbox
3. ?

**Comment by jirhiker** [comment]
this is not the correct place for such discussion. Use Slack for questions and discussion
