### ISSUE TITLE
Jan experiment que - error after first analysis complete

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#938]
active branch=None

active analyses=bu-FC-J-6814

```
Traceback (most recent call last):
  File "/Users/jan/Programming/git/pychron/pychron/core/helpers/exception_helper.py", line 275, in run_with_except_hook
    run_old(*args, **kw)
  File "/Users/jan/anaconda/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/jan/Programming/git/pychron/pychron/experiment/experiment_executor.py", line 450, in _execute
    self._execute_queue(i, exp)
  File "/Users/jan/Programming/git/pychron/pychron/experiment/experiment_executor.py", line 571, in _execute_queue
    self._join_run(spec, run)
  File "/Users/jan/Programming/git/pychron/pychron/experiment/experiment_executor.py", line 666, in _join_run
    self._do_run(run)
  File "/Users/jan/Programming/git/pychron/pychron/experiment/experiment_executor.py", line 734, in _do_run
    run.save()
  File "/Users/jan/Programming/git/pychron/pychron/experiment/automated_run/automated_run.py", line 1037, in save
    self._persister_save_action('post_measurement_save')
  File "/Users/jan/Programming/git/pychron/pychron/experiment/automated_run/automated_run.py", line 1496, in _persister_save_action
    getattr(self.dvc_persister, func)(*args, **kw)
  File "/Users/jan/Programming/git/pychron/pychron/dvc/dvc_persister.py", line 209, in post_measurement_save
    self.active_repository.add(p, commit=False, msg_prefix=msg_prefix)
  File "/Users/jan/Programming/git/pychron/pychron/git_archive/repo_manager.py", line 692, in add
    self._add_to_repo(dest, msg, **kw)
  File "/Users/jan/Programming/git/pychron/pychron/git_archive/repo_manager.py", line 759, in _add_to_repo
    index.add(p)
  File "/Users/jan/anaconda/lib/python2.7/site-packages/git/index/base.py", line 777, in add
    self.entries[(entry.path, 0)] = IndexEntry.from_base(entry)
  File "/Users/jan/anaconda/lib/python2.7/site-packages/gitdb/util.py", line 237, in __getattr__
    self._set_cache_(attr)
  File "/Users/jan/anaconda/lib/python2.7/site-packages/git/index/base.py", line 122, in _set_cache_
    fd = lfd.open(write=False, stream=False)
  File "/Users/jan/anaconda/lib/python2.7/site-packages/gitdb/util.py", line 314, in open
    raise IOError("Lock at %r could not be obtained" % self._lockfilepath())
IOError: Lock at '/Users/jan/Pychron/data/.dvc/repositories/Heizler/.git/index.lock' could not be obtained

```

**Comment by wcmcintosh** [comment]
logger window contents after last quit


'''
AutomatedRun                             -- No value "sensitivity_multiplier" in metadata
ClientExtractionLineManager              -- Invalid valve name=None, description=CO2 Laser to Felix
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
PeakCenter                               -- Peak center failed to move to a baseline position
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
AutomatedRunPersister                    -- No database instance. Not saving post measurement to isotopedb database
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25
SampleBrowserModel                       -- Set "RECENT (hrs)" in Preferences.
"RECENT (hrs)" is located in the "Browser" category
ClientSwitchManager                      -- Valve word length is too short. All valve states will not be updated! Word:5, Num Valves: 25

'''

**Comment by wcmcintosh** [comment]
it appears that valve has multiple names

CO2 to Obama (Pychron computer)
CO2 to Felix (Jan computer)
CO2 to Bone (Felix Mac)

**Comment by wcmcintosh** [comment]
First analysis in queue ran and line is green, but not saved

**Comment by jirhiker** [comment]
same issue as #917. 

Warning message 
```ClientExtractionLineManager -- Invalid valve name=None, description=CO2 Laser to Felix```
not relevant
