### ISSUE TITLE
Extraction Line Scene

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#986]
original
```
extraction line graphic gets wonky over time
```

jirhiker updates
connections are not repositioning correctly when canvas is resized and not at 4:3 aspect ratio

**Comment by jirhiker** [comment]
it doesn't "get wonky over time". Resizing panels/windows both screws it up and fixes it. I think the canvas has to be at a 4:3 ratio for proper viewing

**Comment by wcmcintosh** [comment]
It starts out fine, then loses registration of certain elements over time, seemingly without any resizing
