### ISSUE TITLE
Experiment Queue pause problem

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#987]
Can insert Pause, looks for labnumber, pulldown empty

**Comment by jirhiker** [comment]
is this on jan or felix

**Comment by wcmcintosh** [comment]
jan

**Comment by wcmcintosh** [comment]
On Jan Experiment queue writer, I see that the available lab numbers for blanks, airs, etc. include felix lab numbers as well as Jan lab numbers.  Should they be Jan only, once Jan is selected in the queue pane?

**Comment by jirhiker** [comment]
"lab numbers for blanks, airs, etc. include felix lab numbers as well as Jan lab numbers" is that because you have "Unirradiated" or "NoIrradiation" selected for the irradiation?  The irradiation drop down should be unselected,(default,---,Irradiation) when selecting from "Special Labnumbers"?

**Comment by jirhiker** [comment]
Well what i just said may not be the case. But i consider the labnumber drop down irrelevant when selecting "special labnumbers". 

you can run a pause with any labnumber. just make sure you set the extraction script to "pause" and measurement script to null.
