### ISSUE TITLE
laser shot video

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#989]
Is it possible to start routinely collecting video of laser shots?  Is zooming in prior to firing then zooming back out possible?  I think that you have worked with both of these  ideas previously.

**Comment by jirhiker** [comment]
"set_zoom" is command available in extraction pyscripts. 
recording is also available but im rethinking the storage mechanism. see #988

**Comment by wcmcintosh** [comment]
Time to close this issue?
