### ISSUE TITLE
CO2 enhancement request - not urgent

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#991]
At your convenience, for the CO2:

1. Can CO2 window display power when under remote control? "CO2 on" could be graphic.

2. Add autocenter on hole button, which would trigger hole recognition.

3. Could the second auto-calibration button read autocalibrate  rather autocalibration?

4. Can all calibration functions have a cancel button, that returns calibration to previous state, with the goal of preventing aborted calibration causing trouble.

Thanks,
Bill

**Comment by jirhiker** [comment]
not clear on item 1
