### ISSUE TITLE
minor request - ideogram padding

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#992]
current ideogram default max and min are (max + 1 sigma) and (min-sigma) 
Could we try padding this to 2 sigma, so as not to chop the probability distributions

**Comment by wcmcintosh** [comment]
or use some other approach to padding min and max. Percent? Fixed amount?

**Comment by jirhiker** [comment]
use xpad

**Comment by wcmcintosh** [comment]
OK I see it now
