### ISSUE TITLE
IC Factor - invalids

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#998]
After tagging airs a-01-J-4739 to 4744 as invalid, the invalid analyses continue to be found and plotted as references.  I am also not finding a manual way to remove them from the selected analysis list prior to plotting.  I'll try adding a review node.

**Comment by wcmcintosh** [comment]
No seeing add review node as an option

**Comment by jirhiker** [comment]
likely a caching issue. analyses with a tag="invalid" are excluded from find_references algorithm

**Comment by wcmcintosh** [comment]
A caching issue makes sense.  After restarting pychron, the problem vanished
